### ISSUE TITLE
Create math functions

### ISSUE THREAD

**Issue by pjebs** [antonmedv/expr#112]
Is it possible for this package to do something like this: https://github.com/Sandertv/go-formula/blob/master/README.md

**Comment by antonmedv** [comment]
Yes. Pls, read https://github.com/antonmedv/expr/blob/master/docs/Getting-Started.md
You can pass any functions to expr.

**Comment by pjebs** [comment]
I can't see which functions from math package are acceptable

**Comment by antonmedv** [comment]
You can declare your own or pass from math.
https://play.golang.org/p/5ljasF_IKUC
```go
package main

import (
	"fmt"
	"github.com/antonmedv/expr"
	"math"
)

func main() {
	env := map[string]interface{}{
		"sin": math.Sin,
		"Pi":  math.Pi,
	}

	code := `sin(Pi/2)`

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}

```
