### ISSUE TITLE
FR: Support `len` for map type

### ISSUE THREAD

**Issue by PandaDu** [antonmedv/expr#117]
`len({1: 2, 3: 4})` got error: 
```
 invalid argument for len (type map[string]interface {}) (1:1)
 | len({1: 2, 3: 4})
```

As per [the spec](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md), `len` returns length of array or string. Do you guys have any plan to enable `len` for map type?

**Comment by antonmedv** [comment]
Yes, it will be cool to have it on maps too.

**Comment by antonmedv** [comment]
Fixed.
