### ISSUE TITLE
[Question] How to do case-insensitive string comparison with expr?

### ISSUE THREAD

**Issue by DudePei** [antonmedv/expr#119]
Thanks for your great work!

After reading the langdef carefully, and played with the examples, I want to figure out how to do case-insensitive string comparison with expr? or will you guys add built-in functions like `toLower()` or `toUpper()` as workaround?

**Comment by PandaDu** [comment]
Try this:
```go
env := map[string]interface{}{
	"toLower": strings.ToLower,
}
program, err := expr.Compile(yourCode, expr.Env(env))
```

You can add whatever you want.

**Comment by antonmedv** [comment]
Currently, there are no plans on adding builtins for string manipulation (as well as dates), but such functionality can be really simple added. (See @PandaDu comment) 
Currently, a few operators as (contains, matches, startsWith, endsWith) exists. So, some may be added in the future.
