### ISSUE TITLE
[Feature Request] Override index accessor []

### ISSUE THREAD

**Issue by emicklei** [antonmedv/expr#122]
I would like to evaluate expressions such as:
```
myObject[1]
```
using an Operator override like:

```
expr.Operator("[]", "At")
```
with
```
func (extensions) At(i int)  interface{} {
   ...
}
```

If you think this is useful then I can try to contribute this

**Comment by antonmedv** [comment]
This is very dangerous path what can lead to unmaintainable project. What is problem you are trying to solve?

**Comment by emicklei** [comment]
Well, in my case the variable `myObject` is not a slice but a custom data structure and I would like to hide that implementation detail in the expression.
Can you share why you think this is dangerous to the project?

**Comment by antonmedv** [comment]
* Most of the modern programming languages disallow ALL operator overriding. 
  * And for a reason. 
* It's already complicated with overriddng of binary operators. 
  * Two can overlap each other in unpredictable ways.
* And actually you can do what you want already with patch feature of Expr.

Here is an example: https://play.golang.org/p/GS3JRcJBKBX
```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
	"github.com/antonmedv/expr/ast"
)

func main() {
	code := `Object[5]`

	program, err := expr.Compile(code, expr.Env(Env{}), expr.Patch(&patcher{}))
	if err != nil {
		panic(err)
	}

	env := Env{"hello, world"}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}
	fmt.Print(output)
}

type Env struct {
	Object Object
}

type Object string

func (o Object) Index(i int) string {
	return string(o)[:i]
}

type patcher struct{}

func (p *patcher) Enter(_ *ast.Node) {}
func (p *patcher) Exit(node *ast.Node) {
	n, ok := (*node).(*ast.IndexNode)
	if ok {
		ast.Patch(node, &ast.MethodNode{
			Node:   n.Node,
			Method: "Index",
			Arguments: []ast.Node{
				n.Index,
			},
		})
	}
}
```

Basically you can replace you done with what you want. 
Please take a look at docs: 
* https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md
* https://pkg.go.dev/github.com/antonmedv/expr?tab=doc#example-Patch

**Comment by emicklei** [comment]
thank you for the example
