### ISSUE TITLE
[Bug?] Handle extra whitespace in "not in" syntax

### ISSUE THREAD

**Issue by qu-way** [antonmedv/expr#123]
i.e.
case 1:
```text
"A"  not in ["a", "b", "c"]
```
works and returns `true`

case 2:
```text
"A" not  in ["a", "b", "c"]
```
got panic:
```
panic: unexpected token Operator("not") (1:5)
 | "A" not  in ["a", "b", "c"]
 | ....^
```

do you guys think it's a bug and needs fix? thanks!

**Comment by antonmedv** [comment]
It will be cool to fix it.

**Comment by nmondal** [comment]
I am looking into it. Seems like "not in" is .. hard. It can be made "soft" by splitting it into "apply over" *in* operator.
@antonmedv  that diagnostics, is that right ?

**Comment by antonmedv** [comment]
Yes, not in is ope operator. Possible to split it.

**Comment by nmondal** [comment]
@antonmedv can you please look at it, if it solves it?

**Comment by antonmedv** [comment]
It does, but the solution is really hacky. Can't merge it in this way.

**Comment by nmondal** [comment]
Let me take another stab at it.

**Comment by antonmedv** [comment]
Take a look at accept.
