### ISSUE TITLE
Chained Commands Using Bitwise Operators

### ISSUE THREAD

**Issue by vm1234-code** [antonmedv/expr#126]
I am unable to obtain output from an expression like:
'7 <= 8= < 9'

Rather I have to write 
'7 <= 8 && 7 <= 9'

I was hoping to find help in how to resolve this issue to obtain output using the first expression command.

**Comment by antonmedv** [comment]
Only possible with expr.Patch.

**Comment by vm1234-code** [comment]
Would that require me to modify the ast, optimizer, or operator directory files? Or is expr.Patch another repo I should clone?

**Comment by antonmedv** [comment]
Refer to docs. Also other issues may be helpful.
