### ISSUE TITLE
How to check a key by pattern in map[string]interface{}.

### ISSUE THREAD

**Issue by LokeshBoran** [antonmedv/expr#129]
Allow this for in operator:

contains(key, 'ab') in {abc: 1, b: 2}

or 
has('ab*') in {abc: 1, b: 2}

**Comment by antonmedv** [comment]
You can define helper like this `Keys(map) []string` and do something like:
```js
'ab' in Keys(map)
```

```js
any(Keys(map), {# contains 'ab'})
```

**Comment by LokeshBoran** [comment]
@antonmedv thanks, Ya it's working. I hope there is other way.

But it is good to have some basic methods inbuilt with the package itself like keys, values etc.

By the way thanks man !
