### ISSUE TITLE
Visibility of External Struct Methods

### ISSUE THREAD

**Issue by dschanoeh** [antonmedv/expr#130]
Hi,

I'm trying to use struct methods defined in an external package from within an expression.
Expr cannot find the method:

```
panic: type owm.WeatherData has no method CumulativePrecipitationTill (1:9)
 | weather.CumulativePrecipitationTill(todayAt(20)) > 0.5
 | ........^
```

If instead I define the type (and the method) locally (either in the main package or a different package), the expression compiles without issues.
Is this a limitation or am I missing something?

Below is the example code and the method to be called can be found [here](https://github.com/dschanoeh/go-owm/blob/master/owm.go#L220).

```golang
package main

import (
	"github.com/dschanoeh/go-owm"
	"github.com/antonmedv/expr"
	"time"
)

func main() {
	env := map[string]interface{}{
		"weather":   owm.WeatherData{},
		"todayAt":      todayAt,
	}

	code := `weather.CumulativePrecipitationTill(todayAt(20)) > 0.5`
	_, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}
}

func todayAt(hour int) time.Time {
	now := time.Now()
	t := time.Date(now.Year(), now.Month(), now.Day(), hour, 0, 0, 0, now.Location())
	return t
}
```

**Comment by antonmedv** [comment]
Hi, this is really strange as it should work. In play.golang.com I got same error, but somehow was unable to reproduce it locally:
<img width="833" alt="Снимок экрана 2020-06-21 в 20 56 39" src="https://user-images.githubusercontent.com/141232/85231654-d9302700-b401-11ea-9a18-c43b920bdb33.png">
Everything works. Maybe it depends on what type of go-own lib is used?

**Comment by antonmedv** [comment]
Also, I got this error:
```
go run main.go
go: finding module for package github.com/antonmedv/expr
go: finding module for package github.com/dschanoeh/go-owm
github.com/dschanoeh/go-owm@v0.1.0: verifying module: checksum mismatch
	downloaded: h1:D9xigczE4259sgsLXKXGL1vDl53wG/g8wWncyamS0yY=
	sum.golang.org: h1:UgIqv9uZ54HBKB0BJX4CDAvyv2qMpF6DD0xYdzNyaKo=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by antonmedv** [comment]
I think something with github.com/dschanoeh/go-owm

**Comment by dschanoeh** [comment]
Okay that was very odd. Indeed, just pushing a new release for github.com/dschanoeh/go-owm did the trick.
Sorry to have bothered you and thanks a lot for the great module!
