### ISSUE TITLE
Advice: what you suggest to handle error?

### ISSUE THREAD

**Issue by PxyUp** [antonmedv/expr#131]
Hi, thank for amazing library, but need your advice, for implement our build in function we use function with error arguments, which can not be processed which `map`, `filter`, etc. I found right now only one way for handle error:
```
"last": func (n int) (string) {
      if n == 5 {
      panic("can't process because db not response")
      }
      return fmt.Sprintf("%d", n)
    },
```

Did not find something like that in documentation

**Comment by antonmedv** [comment]
Hi 👋 

Yes, this is the right and safe way of communicating error. 

As evaluation should be safe, recover mechanism was needed.

**Comment by PxyUp** [comment]
So inside function I am should use recovery mechanism, too, or it is save just to throw panic without recovery?

**Comment by antonmedv** [comment]
Yes. Just use panic.

**Comment by PxyUp** [comment]
Thank you
