### ISSUE TITLE
Can not compare two array type value

### ISSUE THREAD

**Issue by CaoYan1** [antonmedv/expr#133]
`

	code0 := `[2889800000000013786] == [a]` // false
	code1 := `[2889800000000013786][:] == [a][:]` // true
	code2 := `[2889800000000013786] == [2889800000000013786]` // true
	env := map[string]interface{}{
		"a": 2889800000000013786,
	}

	p, err := expr.Compile(code0, expr.Env(env))
	if err != nil {
		panic(err)
	}
	output, err := expr.Run(p, env)
	if err != nil {
		panic(err)
	}
	fmt.Println(output)

`

Why is the output of the code1 false

**Comment by antonmedv** [comment]
Expr uses reflect.DeepEqual. And in first example operands have different types. Left side of equation optimised to []int and right side is []interface{}. 
Try to turn off optimisations. Also maybe optimization should not change type.
