### ISSUE TITLE
Allow short circuiting when overriding boolean operators (&&, ||, ...)

### ISSUE THREAD

**Issue by enijns** [antonmedv/expr#134]
Given the following expression:
`missing != nil && missing > 3`

And a custom operator '&&' defined with the following signature:
`func and(a, b interface{}) interface{} ...`

Then running the expression with a nil value for the missing variable results in errors such as:
`could not compare <nil> (<nil>) to 3 (float64)`

I believe the shortcircuiting nature of && could be accomplished using a signature like the following:
`func and(a interface{}) func(interface{}) interface{}`
Unfortunately that is not possible right now.

Maybe there is another way to accomplish what we're after here?

**Comment by antonmedv** [comment]
Short circuit is implemented. But is you override operator and replace it with function there is no way of doing so. I believe what adding such with make expr much more complex and error prone. 

Instead you can try to also patch arguments to your and function to check for nil values.
