### ISSUE TITLE
Accept getter interface in Run() function

### ISSUE THREAD

**Issue by iimos** [antonmedv/expr#135]
Thank you very much for the lib first, it is awesome.

Issue:
Currently Run() func only accepts env of primitive types: map, slice, struct. It means we always should provide values for all posible variables that equation can have. It makes hard using data structures with lazy access to data.

Proposed solution:
I think it would be great if Run() function would also accept env of Getter interface:

```go
type Getter interface {
	Get(interface{}) interface{}
}
```

**Comment by antonmedv** [comment]
I think this can be done right now using [expr.Patch](https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md#patch):

```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
	"github.com/antonmedv/expr/ast"
)

type Env struct{}

func (*Env) Get(name string) string {
	if name == "foo" {
		return "hello"
	}
	return "?" + name + "?"
}

func main() {
	env := &Env{}

	code := `foo + ", " + world`

	program, err := expr.Compile(code, expr.Env(env), expr.Patch(&patcher{}))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}
	fmt.Print(output)
}

type patcher struct{}

func (p *patcher) Enter(_ *ast.Node) {}
func (p *patcher) Exit(node *ast.Node) {
	n, ok := (*node).(*ast.IdentifierNode)
	if !ok {
		return
	}

	ast.Patch(node, &ast.FunctionNode{
		Name:      "Get",
		Arguments: []ast.Node{&ast.StringNode{Value: n.Value}},
	})

}
```

https://play.golang.org/p/7Y4O5BDfkn3

**Comment by iimos** [comment]
It's not as elegant as i'd like it to be. But it works! Thank you. You have made a really good work.
