### ISSUE TITLE
Performance of function calls

### ISSUE THREAD

**Issue by cubewise-tryan** [antonmedv/expr#137]
Hi @antonmedv,

Just wondering whether there is something to optimise calling functions? I am testing out vs GoEvaluate and Expr is fastest except for calling functions. I am not sure the reason but I am guessing it may be due to GoEvaluate only defining functions on the compile step. In the examples below I am just doing a simple addition (float64 + float64) in a function. 

I got some performance improvement by using interface{} for the arguments and return value (`BenchmarkFuncExprFast`), but it still takes twice the time.

```
BenchmarkFuncExpr-12                   	 1428219	       881 ns/op	     208 B/op	       8 allocs/op
BenchmarkFuncExprFast-12               	 1476798	       680 ns/op	     136 B/op	       7 allocs/op
BenchmarkFuncGoEvaluate-12             	 3650031	       332 ns/op	      88 B/op	       4 allocs/op
```

```go
func BenchmarkFuncExprFast(b *testing.B) {

	env := Env{
		"val1": 1.0,
		"val2": 2.0,
		"add": func(args ...interface{}) interface{} {
			return args[0].(float64) + args[1].(float64)
		},
	}

	program, err := expr.Compile(`add(val1, val2)`, expr.Env(env))
	if err != nil {
		b.Error(err)
		b.FailNow()
	}

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		val, err := expr.Run(program, env)
		if err != nil {
			b.Error(err)
		}
		if val != 3.0 {
			b.Errorf("Val %v not 3", val)
		}
	}

}
```

**Comment by antonmedv** [comment]
I think this is due use of reflection. Try to use map instead of Env.

**Comment by cubewise-tryan** [comment]
Using map[string]interface{} instead Env, which was a type alias for map, makes some difference. As a pure map below, I assume that extra alloc is what makes the difference?

```
BenchmarkFuncExpr-12                   	 1342814	       875 ns/op	     208 B/op	       8 allocs/op
BenchmarkFuncExprFast-12               	 2436960	       558 ns/op	     104 B/op	       5 allocs/op
BenchmarkFuncGoEvaluate-12             	 2941843	       379 ns/op	      88 B/op	       4 allocs/op
```

**Comment by antonmedv** [comment]
Yes, this is the case. Try to reuse vm instead of creating new one each time.

**Comment by cubewise-tryan** [comment]
It will be used concurrently, I assume reusing a vm will cause a problem?

**Comment by antonmedv** [comment]
In this case yes.

**Comment by rederry** [comment]
@antonmedv  Wonder it's possbile to avoid use reflection on fetch function to improve performance?

**Comment by antonmedv** [comment]
Yes, currently there is development to add this feature of avoiding reflection at all.

**Comment by rederry** [comment]
> Yes, currently there is development to add this feature of avoiding reflection at all.

Happpy to contribute to it, what can I do 😄
