### ISSUE TITLE
test is failing: too many arguments to call Variadic (1:1)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [antonmedv/expr#139]
Hi.
There is a compilation error, during one of your tests:

> $ go test ./...
> --- FAIL: TestExpr (0.06s)
>     expr_test.go:875: 
>         	Error Trace:	expr_test.go:875
>         	Error:      	Received unexpected error:
>         	            	too many arguments to call Variadic (1:1)
>         	            	 | Variadic("head", 1, 2, 3)
>         	            	 | ^
>         	Test:       	TestExpr
>         	Messages:   	compile error
> FAIL
> FAIL	github.com/antonmedv/expr	0.618s
> ok  	github.com/antonmedv/expr/ast	0.596s
> ok  	github.com/antonmedv/expr/checker	0.536s
> ?   	github.com/antonmedv/expr/cmd/exe	[no test files]
> ok  	github.com/antonmedv/expr/compiler	0.566s
> ?   	github.com/antonmedv/expr/conf	[no test files]
> ok  	github.com/antonmedv/expr/docgen	0.766s
> ok  	github.com/antonmedv/expr/docs/examples	0.598s
> ok  	github.com/antonmedv/expr/file	0.472s
> ok  	github.com/antonmedv/expr/optimizer	0.500s
> ok  	github.com/antonmedv/expr/parser	0.572s
> ok  	github.com/antonmedv/expr/parser/lexer	0.488s
> ok  	github.com/antonmedv/expr/vm	1.396s
> ?   	github.com/antonmedv/expr/vm/generate	[no test files]
> FAIL
> 

My environment:

> $ go env && go version
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfis81/.cache/go-build"
> GOENV="/home/oceanfis81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfis81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfis81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfis81/go_projects/expr/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build239193848=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

I am using [this](https://drive.google.com/file/d/15KD-isorTza_pLjg6l43Bxb1f0QNx4f5/view?usp=sharing) build, for [gollvm](https://go.googlesource.com/gollvm/) compiler ("llvm-goc")
.

**Comment by advancedwebdeveloper** [comment]
CC @thanm @cherrymui @ianlancetaylor

**Comment by ianlancetaylor** [comment]
Thanks, this does appear to be a bug in the gofrontend code.  Filed https://golang.org/issue/41737 (aka golang/go#41737).

**Comment by ianlancetaylor** [comment]
The bug is now fixed in the gofrontend.  This issue can be closed.
