### ISSUE TITLE
go1.8: no type aliases

### ISSUE THREAD

**Issue by agnees** [antonmedv/expr#14]
When I used go get -u github.com/antonmedv/expr, I met vendor/github.com/antonmedv/expr/type.go:9: syntax error: unexpected = in type declaration this error, after troubleshooting go1 .9 is supported, but our production environment is go1.8, how can I solve it?

**Comment by antonmedv** [comment]
yes, looks like 1.8 is too old :)
https://travis-ci.org/antonmedv/expr/builds/444297524
What what added in 1.9?

**Comment by antonmedv** [comment]
Type aliases. Well if your what you can send PR and remove type alias.

**Comment by antonmedv** [comment]
I've did it myself: https://github.com/antonmedv/expr/releases/tag/v1.1.3

**Comment by agnees** [comment]
thx
