### ISSUE TITLE
Why not take it full - and create an awesome scripting language ?

### ISSUE THREAD

**Issue by nmondal** [antonmedv/expr#143]
Whats the plan?
You should totally make it a complete language no?
A full language on top of GO - would be awesome!
JS is sad, rest - there are no competition! 
The direction things are going why don't you explore that?
Do you need more developers ?

**Comment by antonmedv** [comment]
The whole purpose of this package is to be a expression language. Limited feature set is a feature! 
And there is countless programming languages on top of go. Just google it. Expr is just fastest and has seamless integration with go. 
Maybe someday if i have a lot of time, I’ll create my own language.

**Comment by seekerkoruth** [comment]
I thing a full blown language adds bulk and overhead to an expr language. This is unnecessary. I agree with Anton.

**Comment by paralin** [comment]
If you want more scripting features use this: https://github.com/google/cel-go

Expr is for quick expressions to calculate something.

(Probably can close this)
