### ISSUE TITLE
Feature: support max/min operators for numbers

### ISSUE THREAD

**Issue by danysirota** [antonmedv/expr#146]
Hi - thanks for an awesome library, we are using it extensively <3

Today we need to do something like `var1 > var2 ? var1 : var2` for max, and it complicates the expressions.
max(var1, var2) and min(var1, var2) will be really useful and it should be pretty easy, by using the current implementation of the "<" operator.

**Comment by antonmedv** [comment]
You can define your own min/max helpers.

**Comment by danysirota** [comment]
Really? cool.

How? can you share a snippet?

Thanks

**Comment by antonmedv** [comment]
Yes, define in env. ;)

Read docs fully, you gonna find lots of interesting things in it).
