### ISSUE TITLE
any workaround for not having vars?

### ISSUE THREAD

**Issue by asaf** [antonmedv/expr#148]
Hey,

I have a complex nested object such as `foo.bar.arr.qux`, I would like to put this value somewhere (I see there are no vars assignments) and then use it multiple times to construct an object.

Is it possible somehow?

Thanks.

**Comment by antonmedv** [comment]
In other issue I posted an example. Actually I think adding vars will be cool.

**Comment by asaf** [comment]
yea, but need to think this through, currently, expr is super slim and is sort of a one-liner,  changing this will add some complexity.

I saw the other examples, they work ok if you know the vars ahead (so you can declare them on the Env struct level), I have some dynamic parts.

I decided to split expressions into two parts: 1. vars declarations. 2. expressions that use them.

I keep this open as a reminder for adding vars, if you decide to do so.

Thanks!
