### ISSUE TITLE
A new type named set(contain no repeated value) different from the built-in type map

### ISSUE THREAD

**Issue by xiaoyang-chen** [antonmedv/expr#149]
Thanks for your contribution, this library help me a lot.
Now, I receive a requirement from colleagues, he needs a type "set".
The built-in type "map" all contains repeated value, but I want a type that like "map", but without repeating elements， just like type “set” in java， how do i add a new type “set” in this “expr”. @antonmedv 

the new type "set" equal to "map[string]struct{}" in golang

**Comment by antonmedv** [comment]
Just use map[string]struct{} in environment

**Comment by xiaoyang-chen** [comment]
> Just use map[string]struct{} in environment

I use existing types to make a environment like this:
type Lemonx struct {
	ResHits       []*ResHits
	RecordResHits []*RecordResHits
}

type Env struct {
	Lemonx *Lemonx
}
the code is " map(filter(Lemonx.RecordResHits, {.Source.AdjustStage == "free"}), {.Source.AdjustMethod}) "
and from the result of expr.Run(...), I got many "AdjustMethod", but also had many repeated value in the result.
Just what I want is from the result of expr.Run(...), I can get the  "AdjustMethod"(which "AdjustStage" equal to "free") but without repeated value

**Comment by antonmedv** [comment]
You can write you own helper method on env to add such function.

**Comment by xiaoyang-chen** [comment]
> You can write you own helper method on env to add such function.

At the beginning, I done it, had written the function like
func (Env) GetAdjustMethotWithoutRepeatWhenFree(...) {....}
but finally, I write many helper methods like:
func (Env) GetXxxWithoutRepeatWhenXxx().
It looks very ugly and inconvenient, so I want to add a new build-in type like "map" in "expr", but without repeating elements.

**Comment by antonmedv** [comment]
Got it. Currently its not possible to add new builtins (unless using ast.Patch method). Maybe adding reduce() builtin will solve it.

**Comment by antonmedv** [comment]
Why not just add some function like uniq? And apply it to result of map?

**Comment by xiaoyang-chen** [comment]
> Why not just add some function like uniq? And apply it to result of map?

I write "DeduplicateStr(map(filter(Lemonx.RecordResHits, {.Source.AdjustStage == "free"}), {.Source.AdjustMethod}))"
DeduplicateStr(...) function like uniq function what you mean, but finally meet the panic("memory budget exceeded") which in vm.go,line:220

**Comment by antonmedv** [comment]
This safe check to prevent production exhaust cpu. Try increasing it:
vm.MemoryBudget = 1e9

**Comment by xiaoyang-chen** [comment]
> This safe check to prevent production exhaust cpu. Try increasing it:
> vm.MemoryBudget = 1e9

I see "MemoryBudget int = 1e6" in the file vm.go, 
what does "MemoryBudget" mean, the used memory in running expr.Run(..)?

**Comment by antonmedv** [comment]
MemoryBudget is euristic for determining is it's safe to run this expression. For example, consider this:
```
map(1..1e6, {map(1..1e6, {map(1..1e6, {map(1..1e6, {"hello world"})})})})
```
It will easily eat all memory available on the machine, but we can detect it in compile time with "memory budget" analysis.

**Comment by xiaoyang-chen** [comment]
> MemoryBudget is euristic for determining is it's safe to run this expression. For example, consider this:
> 
> ```
> map(1..1e6, {map(1..1e6, {map(1..1e6, {map(1..1e6, {"hello world"})})})})
> ```
> 
> It will easily eat all memory available on the machine, but we can detect it in compile time with "memory budget" analysis.

got it, thanks for your help.
I want to "buy a coffee for you" in your website medv.io, but meet a situation:
![image](https://user-images.githubusercontent.com/61339960/100532711-bb7baf00-3236-11eb-87b3-10a6394fa567.png)
use paypal, but the organization(which I get bank card) do not allow me to pay this bill.
use “借记卡或信用卡”, but it notices me to create a new paypal account, I already have a account,  unable to create a new one,
I want to login and can not find the the entrance.

**Comment by antonmedv** [comment]
Hmmm, you can paypal me directly: paypal.me/antonmedv

**Comment by xiaoyang-chen** [comment]
> Hmmm, you can paypal me directly: https://paypal.me/antonmedv

![image](https://user-images.githubusercontent.com/61339960/100541111-a0cc2900-327c-11eb-92f4-09f0d4eb0092.png)
ok, send successfully, have a nice "coffee"!
