### ISSUE TITLE
Executable bit set for file/*.go

### ISSUE THREAD

**Issue by CyrilBrulebois** [antonmedv/expr#156]
Hi,

While preparing a Debian package for expr (https://bugs.debian.org/978007), I've noticed that `file/*.go` are executable, which seems strange for source files. I've handled that on the packaging side, removing the exec bit in the target location, but I thought I'd let you know, so that it can be adjusted in git and in resulting source tarballs in a later version. ;)

Cheers,
Cyril.

**Comment by antonmedv** [comment]
I removed executable right from those files. Do you need new tag?

**Comment by CyrilBrulebois** [comment]
Thanks! Not at all, I've got a temporary workaround that can stay like that for a while. :)

No rush, I'll get rid of the workaround when a new version is tagged on your side!

**Comment by shmsr** [comment]
Let's close this issue as it's fixed by https://github.com/antonmedv/expr/commit/ddd630dfe874e501ca403579585936deff126451?
