### ISSUE TITLE
Add type conversion builtins

### ISSUE THREAD

**Issue by alexec** [antonmedv/expr#161]
I want to do the following

```golang
expr.Eval("value + 2", map[string]interface{"value": "1"})
````
But value is a string. Casting func?

```golang
expr.Eval("int(value) + 2", map[string]interface{"value": "1"})
```

**Comment by antonmedv** [comment]
Add helper.

**Comment by alexec** [comment]
It would be nice to have build in support.

**Comment by antonmedv** [comment]
I was thinking about it too. But still can’t find good solution what will simple enough to explain to not programmer users of expr.

**Comment by alexec** [comment]
could it be optional? E.g `expr.TypeConvertors()`

In Golang, I think there are only so many conversions you can do. One challenge is if the casting was not sensible due to loss of accuracy (e.g. to float64) or just invalid (the string "foo" to int)

**Comment by antonmedv** [comment]
Yes, we need to find reasonable behaviour in case of loss of accuracy , or other errors.

**Comment by alexec** [comment]
```golang
var castErr error // stash any casting error here
	replaceMap["int"] = func(s string) int {
		v, err := strconv.Atoi(s)
		if err != nil {
			castErr = fmt.Errorf("failed to cast %q to int: %w", s, err)
		}
		return v
	}
	replaceMap["array"] = func(s string) []interface{} {
		array := make([]interface{}, 0)
		if err := json.Unmarshal([]byte(s), &array); err != nil {
			castErr = fmt.Errorf("failed to cast %q to array: %w", s, err)
		}
		return array
	}

	result, err := expr.Eval(expression, bellows.Expand(replaceMap))
	if err == nil {
		err = castErr
	}
	if err != nil {
		return nil, fmt.Errorf("failed to evaluate expression %q: %w", expression, err)
	}
```

**Comment by antonmedv** [comment]
Array cast looks more like Json.parse.

**Comment by alexec** [comment]
One solution to this might be for users to add the Sprig functions. They have a big library and it seems to work nicely:

http://masterminds.github.io/sprig/conversion.html

There are security issues with Sprig methinks, need to understand what sub-set of commands are safe.

**Comment by paralin** [comment]
I think adding some basic casting based on https://github.com/spf13/cast would be useful.

toFloat, toString, ...

**Comment by Dentrax** [comment]
Looking forward to this enhancement. It would be a massive life-saving feature by avoiding putting custom patch functions in every time into map.

I was thinking about this, maybe you can introduce a new Node type: `ConversionNode` with a new OpCode: `OpConversion`. (IDK there is already a `OpCast` opcode, it [seems to do something](https://github.com/antonmedv/expr/blob/497c6bd01cf837ecda6a2644e5e1868a26fabd9f/vm/vm.go#L353) for the [config.Expect](https://github.com/antonmedv/expr/blob/497c6bd01cf837ecda6a2644e5e1868a26fabd9f/compiler/compiler.go#L34) stuff) - don't know much about the internals, just using the keywords as a placeholder.

> But still can’t find good solution what will simple enough - @antonmedv

What about:
* `float64(Foo.Bar)`
* `int("Baz.Qux")`
* `string(Quux)`

If conversion fails, the `Compile()` func should return an error.

**Comment by antonmedv** [comment]
Added `int()` and `float()`.
