### ISSUE TITLE
Add reduce() and group() builtins

### ISSUE THREAD

**Issue by alexec** [antonmedv/expr#162]
It would be good to complete this set of operations.

I think group would be:

```
group(Prices,  {# > 10})
```

But I'm not sure the closure syntax can support reduce op due to the need for the closure to take two args, something like

```
reduce(Prices, 0, {.value + .acc})
```

**Comment by antonmedv** [comment]
Yes, I’m also thinking about reduce built in for some time. Two arguments maybe done with for example #1, #2 or #acc named parameters. 

But what should group func do?

**Comment by alexec** [comment]
Group should partition an array into other arrays based on a key. Like SQL group by

**Comment by antonmedv** [comment]
So it should return a map?

**Comment by alexec** [comment]
I'm not sure. It could be an array of arrays, but the downside would be that you don't then know what the grouping key was.

I think the ultimate litmus test would be - can you do Hadoop style map-reduce?

https://techmytalk.com/2014/11/07/hadoop-mapreduce-group-by-operation-part1/#:~:text=The%20grouping%20of%20map%20output,the%20Map%20to%20the%20Reducer.

**Comment by alexec** [comment]
@antonmedv I'm not sure I'm skilled enough to write these on my own, could we get one a Zoom and you show me how please?

**Comment by mhr3** [comment]
+1 for reduce, perhaps more than one param could be done by extending closures with a js-like "header" `(x,y,z) => {...}`, where the header is optional, and when not present basically becomes `(#) => `?

**Comment by antonmedv** [comment]
Yes, also was thinking about `(params) => {...}` style. But what about `{x, y => ...}`?

**Comment by mhr3** [comment]
Look like a closure returning two values: `x` and a bool :)

**Comment by antonmedv** [comment]
`{#1 >= #2}`

**Comment by pritamdey12** [comment]
@antonmedv Hi, is there any update on the `reduce` built-in function?

**Comment by pritamdey12** [comment]
@antonmedv Hi, any update on the `reduce` function?

**Comment by antonmedv** [comment]
Nope.

**Comment by forrestlinfeng** [comment]
> So it should return a map?

yes, this feature is useful like as slice to map。

**Comment by antonmedv** [comment]
Also added 
```
countBy(1..100, # % 7)
```

**Comment by antonmedv** [comment]
Added reduce

```
reduce(1..9, # + #acc)
reduce(1..9, # + #acc, 0)
```
