### ISSUE TITLE
Store compiled vm.Program to redis

### ISSUE THREAD

**Issue by mmta41** [antonmedv/expr#178]
How to store compiled scripts to redis/keydb?

**Comment by antonmedv** [comment]
Currently there is no way of doing this. It’s like storing compiled regex - not possible and not needed in go  

Besides what is your motivation for storing compiled program? If it’s a speed, compilation itself is quite quick.

**Comment by mmta41** [comment]
Yes it's speed and also replicate through redis cluster, so all nodes in my cluster have identical list of programs at time

**Comment by antonmedv** [comment]
Just spread program code and compile it every there. I doubt what it can have any performance lost.
