### ISSUE TITLE
Too rough check for abstract maps

### ISSUE THREAD

**Issue by eyudkin** [antonmedv/expr#179]
Hi, first of all thank you very much for such awesome library, it helps me a lot. Anyway, I faced a few issues related with type checks: using `map[string]interface` values:

### First case when using structs
Expr doesnt check for real map value types. Playground example: https://play.golang.org/p/FY-y9Puhbap
Brief code:
```go
code := `ParseDecimal("1")+Params.Foo`
	env := map[string]interface{}{
		"Params": map[string]interface{}{
			"Foo": decimal.NewFromInt(2),
		},
		"ParseDecimal": func(s string) decimal.Decimal {
			d, err := decimal.NewFromString(s)
			try(err)
			return d
		},
		"Add": func(a, b decimal.Decimal) decimal.Decimal { return a.Add(b) },
	}
```
Causes 
```
panic: invalid operation: + (mismatched types decimal.Decimal and interface {}) (1:18)
 | ParseDecimal("1")+Params.Foo
 | .................^
```
Because operands check compares `decimal.Decimal` (left) with the `map[string]interface{}`->valueType->`interface{}` (right). I think checker should take `Params.Foo` value and then compare its type instead of checking value type from the map definition.

### Second case when using primitive types
Expr doesnt check map value types properly for primitive types at compilation type, it checks types in runtime instead. Playground example: https://play.golang.org/p/7DNfCF48RzR
Brief code:
```go
code := `1+Params.Foo`
	env := map[string]interface{}{
		"Params": map[string]interface{}{
			"Foo": "test",
		},
	}
	options := []expr.Option{
		expr.Env(env),
	}

	program, err := expr.Compile(code, options...)
	try(err, "compile err")

	output, err := expr.Run(program, env)
	try(err, "run err")
```
Causes 
```
panic: run err: invalid operation: int + string (1:2)
 | 1+Params.Foo
 | .^
```
but should cause
```
panic: compile err: mismatched types: int + string (1:2)
 | 1+Params.Foo
 | .^
```

**Comment by antonmedv** [comment]
With the second case everything is right. Expr doesn't see env as whole/nested definition and properly thinks what map values in interface{}. At compile step only information about env structure is used. For example this is what compile steps sees:
```go
	env := map[string]interface{}{
		"Params": map[string]interface{}{},
	}
```

For first case, please, provide playground example.

**Comment by eyudkin** [comment]
Provided it in first message:
> Expr doesnt check for real map value types. 
> Playground example: 
> https://play.golang.org/p/FY-y9Puhbap

**Comment by antonmedv** [comment]
Well. It’s same. Only first level object types are used. So Params.Foo is interface{} and no operator overload takes place.

**Comment by eyudkin** [comment]
But that makes type-dependent operator overload pretty useless: it forces me to describe all operations like interface{} +interface{} and check types in runtime.
BTW, why don't you want to fetch map values and compare it real values in compile time? That makes types check weaker than it could be.

**Comment by antonmedv** [comment]
Yes, it's possible to extend the type checker to also use this information. But for example what type is Params.Rttt?
