### ISSUE TITLE
Array type conversions break method dispatch

### ISSUE THREAD

**Issue by kamstrup** [antonmedv/expr#188]
Suppose I want to expose a `join(arr, sep)` function that joins an array of any types of elements by coercing them to strings and joining them with a separator.

This is currently not possible with expr because of the way array types are converted.

If my Go code looks like this:
```.go
func Join(arr []interface{}, string sep) string {
	b := strings.Builder{}
	for i, e := range arr {
		if i > 0 {
			b.WriteString(sep)
		}
		b.WriteString(myToString(e))
		
	}
	return b.String()
}
```

This call will work: `join([1, "two"], " ")`

And these will fail (because arr is of type []int and []string respectively): `join([1, 2], " ")`, and `join(["one", "two"], " ")`.

Not sure how to go about this... I could maybe patch the AST, but it could also be added as a compiler opt?

**Comment by antonmedv** [comment]
Join(arr interface{}, string sep) string

**Comment by kamstrup** [comment]
Thanks for the suggestion :+1:
