### ISSUE TITLE
Map Access does not have check

### ISSUE THREAD

**Issue by seekerkoruth** [antonmedv/expr#191]
I am trying to put a check in map access. 

if you have a Golang map foo and it **does not** have an element "bar" the code below will fail silently without an error message regarding non existent map element. It returns a 0 and the silent nature of this substitution and error can create issues.

` foo.bar+1`

I suggest  in line 37 of runtime.go: 

```go
	case reflect.Map:
		value := v.MapIndex(reflect.ValueOf(i))
		if value.IsValid() {
			if value.CanInterface() {
				return value.Interface()
			}
		} else {
			panic(fmt.Sprintf("%v not found", i))        // this is the addition
			//elem := reflect.TypeOf(from).Elem()       // this is commented
			//return reflect.Zero(elem).Interface()       // this is commented
		}

```

Thank you.

**Comment by antonmedv** [comment]
I don’t remember the logic behind this behaviour. Maybe @davidklassen has some thoughts?

**Comment by seekerkoruth** [comment]
> I don’t remember the logic behind this behaviour. Maybe @davidklassen has some thoughts?

Anton,

The above code fragment will fix it.  runtime.go:37

**Comment by antonmedv** [comment]
Not just a fix. Expr will behave differently.

**Comment by seekerkoruth** [comment]
> Not just a fix. Expr will behave differently.

@antonmedv,

Understood. However it will be in the line of other checks made such as a slice index out of bounds error. Etc.

bar not found (1:5)
 | foo.bar+1
 | ........^

Respectfully.

**Comment by seekerkoruth** [comment]
Regardless .. excellent work with the rest.

**Comment by antonmedv** [comment]
Added a such check, fixed in master.
