### ISSUE TITLE
Eval() or Run() not returning an error.

### ISSUE THREAD

**Issue by loosbrecht** [antonmedv/expr#198]
I'm trying to use a rule that is able to return an error. But I only get the first return value back.

I even tried to use the example code but even there I don't get an error back.
The code below prints out `0` and not the error as expected.

```
package main

import (
	"errors"
	"fmt"
	"github.com/antonmedv/expr"
)

func main() {
	env := map[string]interface{}{
		"foo": -1,
		"double": func(i int) (int, error) {
			if i < 0 {
				return 0, errors.New("value cannot be less than zero")
			}
			return i * 2,nil
		},
	}

	out, err := expr.Eval("double(foo)", env)

	// This `err` will be the one returned from `double` function.
	// err.Error() == "value cannot be less than zero"
	if err != nil {
		panic(err)
	}
	fmt.Print(out)
}

```
p.s. [Returning errors](https://github.com/antonmedv/expr/blob/master/docs/Custom-Functions.md#returning-errors) contains an error in the example at line 16. This should be `return i * 2, nil`

**Comment by antonmedv** [comment]
@ffenix113 can you take a look, please? As you implemented this feature 😊

**Comment by ffenix113** [comment]
@antonmedv here is PR for fixing documentation: https://github.com/antonmedv/expr/pull/199

As for code not returning errors - I think solution is rather simple: new tag needs to be created to include this changes. Because doing something like `go get github.com/antonmedv/expr@master` will panic properly for this example.

**Comment by antonmedv** [comment]
Released https://github.com/antonmedv/expr/releases/tag/v1.9.0
