### ISSUE TITLE
Q: How can I extract all the names of an expression?

### ISSUE THREAD

**Issue by Mistobaan** [antonmedv/expr#20]
Assuming I have a document `map[string]interface{}{ "Age" : ..., "Income": ..., "other" : .... }`, and a generic expression. 
I want to be able to know all the `names` that are in the expression. 
```golang
> expr.GetNames("Age > 25 AND Income > 25,000" ) 
[ "Age", "Income"]
```

**Comment by antonmedv** [comment]
Visitor will help with this. But now it isn’t implemented, so there is no way now of extracting names. But I think this is good feature and if I have time, I’ll implement it.

**Comment by antonmedv** [comment]
Now it's possible:

[ast](https://godoc.org/github.com/antonmedv/expr/ast) package provides `Visitor` interface and `BaseVisitor` implementation. 
You can use it for traveling ast tree of compiled program.

For example if you want to collect all variable names:

```go
import "github.com/antonmedv/expr/ast"

type visitor struct {
	ast.BaseVisitor
	identifiers []string
}

func (v *visitor) IdentifierNode(node *ast.IdentifierNode) {
	v.identifiers = append(v.identifiers, node.Value)
}

program, err := expr.Compile("foo + bar", expr.Env(env))

visitor := &visitor{}
ast.Walk(node, visitor)
	
fmt.Printf("%v", visitor.identifiers) // outputs [foo bar]

```
