### ISSUE TITLE
Any way to make numbers/result float64 by default?

### ISSUE THREAD

**Issue by simon-anz** [antonmedv/expr#202]
Hi. Is there any way in code to make the expression evaluate all static numbers as floats rather than ints?   Am using expr to allow end-users to enter simple expressions in places where numbers would normally be used, but if they do "5/2" they get (int)2 rather than (float)2.5.  It would be too hard to explain to all users of the software that they should use "5.0/2". Thanks!

**Comment by antonmedv** [comment]
This is possible to do via expr.Patch.

**Comment by simon-anz** [comment]
OK, good lead. Is this right?

```golang
// AST Visitor that changes Integer to Float
type patcher struct{}

func (p *patcher) Enter(_ *ast.Node) {}
func (p *patcher) Exit(node *ast.Node) {
	n, ok := (*node).(*ast.IntegerNode)
	if ok {
		ast.Patch(node, &ast.FloatNode{Value: float64(n.Value)})
	}
}

func EvaluateExpressionToFloat64(input string) (float64, error) {
	input = strings.TrimSpace(input)
	if input == "" {
		return 0, nil
	}
	program, err := expr.Compile(input, expr.Env(nil), expr.Patch(&patcher{}))
	if err != nil {
		return 0, err
	}
	result, err := expr.Run(program, nil)
	if err != nil {
		return 0, err
	}
	f64, ok := result.(float64)
	if !ok {
		return 0, errors.New("could not type assert float64")
	}
	return f64, nil
}
```

**Comment by simon-anz** [comment]
The code in previous post works; enough for me; closing issue.

**Comment by Harlan6** [comment]
It not works in vesion 1.19

**Comment by antonmedv** [comment]
Latest version is [v1.15.3](https://github.com/antonmedv/expr/releases/tag/v1.15.3)
