### ISSUE TITLE
Fetcher Interface

### ISSUE THREAD

**Issue by seekerkoruth** [antonmedv/expr#204]
How exactly should this be implemented:

To fetch fields from struct, values from map, get by indexes expr uses reflect package. Envs can implement vm.Fetcher interface, to avoid use reflect:

``` go
type Fetcher interface {
	Fetch(interface{}) interface{}
}
```

I mean considering the following struct .. how does one implement this optimization?

```go
type foo struct {
i int,
f float64,
s string
}
```
Thank you.

**Comment by nidorx** [comment]
Maybe this PR will answer https://github.com/antonmedv/expr/pull/254

**Comment by antonmedv** [comment]
Unexported fields cannot be accessed.
