### ISSUE TITLE
eval of equality comparison between string and int

### ISSUE THREAD

**Issue by hkoketsu** [antonmedv/expr#205]
I would like to know if this is your intended behaviour or could be a bug. I was expecting the following code would give error since compared types are different, but actually it did not and returned a value of `false`.

```
env := map[string]interface{}{
    "a": "1",
    "b": 1,
}
out, err := expr.Eval("a == b", env)
```

Digging into your code, I found that this is because no type checking has been applied in this case until it reaches `reflect.DeepEqual(a, b)`  (https://github.com/antonmedv/expr/blob/master/vm/helpers.go#L345). 

Let me know what you think about. Thanks!

**Comment by antonmedv** [comment]
Yes, to speed up Eval type checker is omitted. 

Use Complie and Run to enable type checker.

**Comment by hkoketsu** [comment]
I see, thanks for the clarification.
