### ISSUE TITLE
Sandboxing expression

### ISSUE THREAD

**Issue by alexec** [antonmedv/expr#206]
We want to be able to sandbox expression evaluation, because some users might submit time, memory, or CPU intensive expression, either accidentally, or as a intentional attack of code that uses expr, example

```
map(0..10000, {sprig.genPrivateKey('rsa')}
```

**Comment by alexec** [comment]
But perhaps timeout of 1s would prevent much memory usage.

**Comment by antonmedv** [comment]
See https://github.com/antonmedv/expr/issues/260
