### ISSUE TITLE
Normalizing exported struct fields

### ISSUE THREAD

**Issue by dpogorzelski** [antonmedv/expr#213]
Hey there :)
Please consider the following:

```go
type Instance struct {
	PublicAddress  string
	PrivateAddress string
	Name           string
	Labels         map[string]string
}

program, err := expr.Compile(target, expr.Env(Instance{}), expr.AsBool())
.......
```

I can now evaluate the following expression `Name == "foobar"` but not `name == "foobar"` since `Name` is an exported field and thus starts with a capital letter. What would be the best practice here to be able to use lowercase/case insensitive field names in the expressions?
Thanks

**Comment by antonmedv** [comment]
What about adding expr.Option for case insensitive vars and names?
```go
expr.CaseInsensitive()
```

**Comment by dpogorzelski** [comment]
That would be handy :)

**Comment by antonmedv** [comment]
PR are welcome ;)

**Comment by dpogorzelski** [comment]
Haha yep, i'm gonna look into it :)

**Comment by antonmedv** [comment]
Now Expr has `expr:"name"` tags!
