### ISSUE TITLE
How to compare a string with a int64?

### ISSUE THREAD

**Issue by vadzxd** [antonmedv/expr#214]
func main() {
	env := map[string]interface{}{
		"number": "123",
	}

	code := "number > 100"

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}

--------------
panic: invalid operation: > (mismatched types string and int) (1:8)
 | number > 100
 | .......^

-------------
How can I transfer the string type number to int64?

**Comment by vadzxd** [comment]
Thank you very much！

**Comment by antonmedv** [comment]
https://stackoverflow.com/questions/21532113/golang-converting-string-to-int64
