### ISSUE TITLE
Feature request - automatic cast for integer

### ISSUE THREAD

**Issue by daisy1754** [antonmedv/expr#215]
This expression with below function will cause the runtime error because of type - `reflect: Call using int as type int64`.

It would be nice if expr can automatically cast int to int64 in this case

```
User.AccountAge < MinutesToMillis(7)
```

```
func (e Env) MinutesToMillis(min int64) int64 {
	return int64(min * 60 * 1000)
}
```

**Comment by antonmedv** [comment]
Done! Even bin op can be used:
```
MinutesToMillis(7+2)
```
