### ISSUE TITLE
How to access to a field with dot in its key?

### ISSUE THREAD

**Issue by MoonlitAlley** [antonmedv/expr#228]
i got a problem like this: https://github.com/antonmedv/expr/issues/106

`
	env := map[string]interface{} {
		"xxx.xx": map[string]interface{} {
			"yyy.yy": true,
		},
	}
`
how to get the value of "xxx\\.xx.yyy\\.yy"

Thanks for replying

**Comment by antonmedv** [comment]
Foo[“bar.baz”]

**Comment by MoonlitAlley** [comment]
i will try it later
