### ISSUE TITLE
[question]: how attribute result to each bool expression.

### ISSUE THREAD

**Issue by yeqown** [antonmedv/expr#231]
I have such expression `cond1 && cond2 || cond3`, after I get bool result, but how could I know which condition was failed? In my thought, preloading some fuzzy remarks may be helpful, but what should it looks like, I have no idea now

any advise would be helpful, thanks

**Comment by antonmedv** [comment]
Split expression and test parts.

**Comment by yeqown** [comment]
en~ that sounds awkward 😂  although it's a way to accomplish
