### ISSUE TITLE
how to get array element in any operation

### ISSUE THREAD

**Issue by KoalaInTree** [antonmedv/expr#233]
i want to get this function. 
`func HitKeyword() bool {
	keywords := []string{"foo", "bar"}
	content := "foooo"
	for _, keyword := range keywords {
		if strings.Contains(content, keyword) {
			return true
		}
	}
	return false
}`

then i use expr like this
`keywords := []string{"foo", "bar"}
	content := "foooo"
	code := "any(keywords,{content contains .})"

	env := mockMapStringStringEnv{}
	env["content"] = content
	env["keywords"] = keywords

	options := []expr.Option{
		expr.Env(env),
		expr.AllowUndefinedVariables(), // Allow to use undefined variables.
	}

	program, err := expr.Compile(code, options...)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}

	output, err := expr.Run(program, env)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}
	fmt.Printf("%v", output)`

some err happend： 
`expected name (1:34)
 | any(keywords,{content contains .})
 | .................................^`

how to fix it

**Comment by antonmedv** [comment]
any(keywords,{content contains #})

**Comment by KoalaInTree** [comment]
thx
