### ISSUE TITLE
getFunc() for arbitrary types

### ISSUE THREAD

**Issue by timesselens** [antonmedv/expr#24]
in func getFunc(val interface{}, name string) (interface{}, bool)
there is a switch on d.Kind()

is it possible to add a default for the switch? ie:
```
   default:
        method := v.MethodByName(name)
        if method.IsValid() && method.CanInterface() {
            return method.Interface(), true
        }

```
this way it would be possible to allow methods on arbitrary types, 

```
type X int
func (x X) PrintFormat() { ... }
type B struct { A X }

exp.Eval(`A.PrintFormat()`,B{A:X(10)})

```

**Comment by antonmedv** [comment]
Yes, this will be cool. I’ll fix it today.

**Comment by antonmedv** [comment]
This should be fixed now. Try to update expr to master version.

**Comment by antonmedv** [comment]
https://github.com/antonmedv/expr/blob/master/vm/runtime.go#L52
