### ISSUE TITLE
define expr global variables ?

### ISSUE THREAD

**Issue by AprilFiv** [antonmedv/expr#240]
Can we set some variables into env and use them in custom functions?

**Comment by antonmedv** [comment]
You can do it via method. Define custom func on env struct and access var from env.

**Comment by AprilFiv** [comment]
> You can do it via method. Define custom func on env struct and access var from env.

thanks to replay.

**Comment by AprilFiv** [comment]
> You can do it via method. Define custom func on env struct and access var from env.

Thanks to reply.  I mean if we use a custom func to set some variables, can we use them in another custom func?

**Comment by AprilFiv** [comment]
> You can do it via method. Define custom func on env struct and access var from env.

I have known we could use env in script, I didn't notice any api of package to support custom function use env, may be a reference...

**Comment by antonmedv** [comment]
I'm working on variables)

**Comment by antonmedv** [comment]
Duplicate of #101
