### ISSUE TITLE
Slices and last element of an array

### ISSUE THREAD

**Issue by christophkreutzer** [antonmedv/expr#246]
According to https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md#slices it is possible to slice arrays with various options. However I don't see an option to retrieve the last element of an array.

I tried `array[:-1]` but that doesn't seem to work. Is this case not supported or is the syntax different?

Use Case:
I'm using Argo Workflows with Bitbucket webhooks, and would like to extract the last commit hash of the changes array.

**Comment by antonmedv** [comment]
I’m not sure. Let’s check code.

**Comment by roqenrox** [comment]
This sounds like a use case for the [patch method](https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md#patch), doesn't it?

**Comment by antonmedv** [comment]
Expr uses https://pkg.go.dev/reflect#Value.Index
So this is not possible to do yet. But yes, Patch can help, or we can add it to the code.
