### ISSUE TITLE
Support long jumps inside an expression

### ISSUE THREAD

**Issue by danysirota** [antonmedv/expr#248]
We are generating really long expressions (>1MB) and using conditionals there that can cause more than 64KB jumps.
Today, the args of the opcodes are 2 bytes and long jumps are truncated to this size.
When running the expression, the VM jumps (actual_offset % 64Kb) and runs invalid opcodes.

**Comment by antonmedv** [comment]
Wow! Such a big expression. Amazing) So, yes. this is a limitation of the current VM. 

I see to possible solutions:

1. Use bigger opcodes (this will require proper benchmarking to make sure be op size performance as the same level).
2. Or panic on trying to generate too big jump.

**Comment by antonmedv** [comment]
Fixed! I refactored vm. Now it uses int for args. So, jumps can be really long. Also it got 50% faster).
