### ISSUE TITLE
allow @ character in lexer

### ISSUE THREAD

**Issue by tooptoop4** [antonmedv/expr#250]
fixes https://github.com/argoproj/argo-workflows/issues/8734

**Comment by antonmedv** [comment]
Foo[“bar@“]

**Comment by tooptoop4** [comment]
@antonmedv "workflow.parameters.message.@fromstr.Records.0.s3.object.key" does not work, the @ is needed for gjson lib

**Comment by antonmedv** [comment]
Don’t know what it means.

**Comment by tooptoop4** [comment]
case r == '@':
		l.backup()
		return identifier

I think adding that in https://github.com/antonmedv/expr/blob/baae791a9321e8570785ea18814d0697057b2a00/parser/lexer/state.go#L47 will fix it

**Comment by antonmedv** [comment]
I don’t see a problem. Why expr should support it?
