### ISSUE TITLE
What is the expr equivalent of this govaluate's arbitrary expression code?

### ISSUE THREAD

**Issue by Dentrax** [antonmedv/expr#261]
I'm researching if I can move to expr from the [govaluate](https://github.com/Knetic/govaluate) dependency since it's not maintaining anymore. And I'm wondering about how can I achieve the following using expr:

```go
expression, err := govaluate.NewEvaluableExpression("foo > 0");

parameters := make(map[string]interface{}, 8)
parameters["foo"] = -1;

result, err := expression.Evaluate(parameters);
```

It would be nice to have a migration guide for _govaluate -> expr_. Thanks!

**Comment by antonmedv** [comment]
Exactly the same. Please read the manual.
