### ISSUE TITLE
New member fetch optimizations

### ISSUE THREAD

**Issue by gitperson1980** [antonmedv/expr#263]
Anton,

Can you explain how the new member fetch optimizations work? 

Thank you

**Comment by antonmedv** [comment]
On compile step, expr extracts field indexes and on run step uses v.FieldByIndex. 

This optimisation is faster than using old vm.Fetcher interface.

**Comment by antonmedv** [comment]
On compile step, expr extracts field indexes and on run step uses v.FieldByIndex. 

This optimisation is faster than using old vm.Fetcher interface.

**Comment by gitperson1980** [comment]
Interesting optimization. Might this method work on lowercase (un-exported) fields? Thank you.

**Comment by antonmedv** [comment]
If field is unexported it’s impossible to access it outside origin module. 

You can rename fields with `expr:””` tag.

**Comment by gitperson1980** [comment]
Thank you. Expr tag is a good feature.  I look forward to using the optimization. One thing fetcher provided was a way to provide virtual or derivative fields without creating functions.

case  "foo":
  return x+1/2+y

**Comment by antonmedv** [comment]
Derivative vars can be implemented using ast.Patcher: replace IdentifierNode with CallNode.

**Comment by gitperson1980** [comment]
I assume that fast functions still continue to work without issue considering that it was dependence on the fetcher interface in the past.

**Comment by antonmedv** [comment]
Even better. FastCall now can be on any level: function call, method call.
