### ISSUE TITLE
Move vm/debug/ to a new repository

### ISSUE THREAD

**Issue by ilius** [antonmedv/expr#265]
Looking at dependencies, I was surprised to see `tcell` and `tview`, because they are user interface libraries! An expression parsing/evaluation library should not depend on user interface. So I `grep`ed and saw that they are only used in `vm/debug/debugger.go`.

Is it possible to move the debugger to a new repository and remove these dependencies (and their dependencies)?

**Comment by antonmedv** [comment]
Added a separate module https://github.com/antonmedv/expr/tree/master/debug

Let's see it it will work.

**Comment by antonmedv** [comment]
Done: https://github.com/antonmedv/expr/tree/master/debug
