### ISSUE TITLE
Type Def issues

### ISSUE THREAD

**Issue by gitperson1980** [antonmedv/expr#271]
A slight issue  in the new optimized paradigm

``` go

type BarArray  []float64

type Foo struct {
  Bar  BarArray
  Baz int
}
```

expr  Foo.Bar[0] will fail
interface conversion: interface {} is int, not string  | Foo.Bar[0]

following will work fine as Bar is defined as an intrinsic type

``` go

type Foo struct {
  Bar []float64
  Baz int
}

```

Can there be a resolution to this?  Thank you.

**Comment by gitperson1980** [comment]
I am going to provide a working example.

**Comment by antonmedv** [comment]
Yes, will fix it. Please, provide full code example.

**Comment by antonmedv** [comment]
Actually, I can't reproduce it. Everything seems to work fine: https://github.com/antonmedv/expr/commit/2368f722dc7d15bfec122e8f276e2c5dc15ef919
