### ISSUE TITLE
New Optimizations still uses a lot of reflection

### ISSUE THREAD

**Issue by gitperson1980** [antonmedv/expr#273]
The new optimizations make heavy use of reflection and is slower than the fetcher methods. Will fetcher be still available as a fall back?

![image](https://user-images.githubusercontent.com/97617206/200098940-5fa7abda-3cda-47a7-a0db-8125f1ec91b9.png)

**Comment by antonmedv** [comment]
From my benchmarks, a fetcher is not needed. New optimizations use reflect. But looks like it's much faster, faster than Fetcher.

**Comment by antonmedv** [comment]
Here is an example: I generated Fetcher for real_world example: https://github.com/antonmedv/expr/pull/274

It performs 50% worse. 

<img width="866" alt="Снимок экрана 2022-11-05 в 13 19 42" src="https://user-images.githubusercontent.com/141232/200119636-8e2cbe95-13f6-4995-b9fa-d6c9338d49db.png">

**Comment by antonmedv** [comment]
Also, please, show  expressions you’re using. Maybe I can find some way to improve vm.

**Comment by gitperson1980** [comment]
Anton .. thank you for the test. I will make note of it. I think some of my issues were around access to maps and functions. Maps .. I can't do anything about .. although I hardcoded certain static maps with their items into a pointer in the struct and accessed in the fetcher which avoided the lookup - and I accessed them directly in the language.  Fetcher was used since these pointers were un-exported. The other issues I had were around functions but the interface{} parameter fastcall method solved some of those issues since I put the functions in the env struct fetched by fetcher  whereas the non-fastcall methods in the struct used heavy reflection.  I will test further.. I believe you are right in that it appears you are using offsets to the variables this time which should be faster.

**Comment by gitperson1980** [comment]
Let me get some example together.

**Comment by gitperson1980** [comment]
The expressions are fairly simple.
It uses Fetch for anything that requires slices access via index or map access via key.
It uses FetchField for anything that is an element of a struct.
``` go
type  Exmp  struct {

foo  []float64  // uses Fetch
bar map[string]float64 //uses Fetch
baz int            // uses FetchField
baz2 func(...interface{}) interface{}  //uses FetchField
}
```
Expressions would be
``` go
var e Exmp;

 e.foo > 1
e.bar["test"] > 1.0
e.baz < 1.0
e.baz2(1) > 1
```

**Comment by antonmedv** [comment]
Yes, sounds about right. I think this is how it should behave.
