### ISSUE TITLE
Add quotient operator `\` to allow integer arithmetic

### ISSUE THREAD

**Issue by xio812** [antonmedv/expr#278]
Since [`bd73b5a`](https://github.com/antonmedv/expr/commit/bd73b5abbf49e0c59f3100b76c53fdc4e9afc8a0) the division is done using floating point numbers by default, i.e. `a/b := float64(a) / float64(b)`.

For users who explicitly perform integer arithmetic, this makes the hurdle of using `expr` much greater.

Therefore I propose the introduction of a [quotient operator `\`](https://mathworld.wolfram.com/Quotient.html) which performs an integer division, i.e. `1\2==0` whereas `1/2==0.5`.

**Comment by antonmedv** [comment]
What about adding it as a builtin function `quotient(a, b)`?

BTW, I really like Mathematica. 👍🏻
