### ISSUE TITLE
Add builtin math functions

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/expr#279]
- `abs(x)`
- `acos(x)`
- `acosh(x)`
- `asin(x)`
- `asinh(x)`
- `atan(x)`
- `atan2(y, x)`
- `atanh(x)`
- `cbrt(x)`
- `ceil(x)`
- `cos(x)`
- `cosh(x)`
- `dim(x, y)`
- `erf(x)`
- `erfc(x)`
- `erfcinv(x)`
- `erfinv(x)`
- `exp(x)`
- `exp2(x)`
- `expm1(x)`
- `fma(x, y, z)`
- `floor(x)`
- `gamma(x)`
- `hypot(p, q)`
- `ilogb(x) int`
- `j0(x)`
- `j1(x)`
- `jn(n int, x)`
- `ldexp(frac, exp int)`
- `log(x)`
- `log10(x)`
- `log1p(x)`
- `log2(x)`
- `logb(x)`
- `max(x, y)`
- `min(x, y)`
- `mod(x, y)`
- `pow(x, y)`
- `pow10(n int)`
- `remainder(x, y)`
- `round(x)`
- `roundtoeven(x)`
- `sin(x)`
- `sinh(x)`
- `sqrt(x)`
- `tan(x)`
- `tanh(x)`
- `trunc(x)`
- `y0(x)`
- `y1(x)`
- `yn(n int, x)`

**Comment by antonmedv** [comment]
Also add #278

**Comment by antonmedv** [comment]
Probably in math namespace.

```
math.sin(math.pi)
```

**Comment by antonmedv** [comment]
Added max and min.

**Comment by lukas-vollmer** [comment]
push. Mainly for round, floor, ceil
