### ISSUE TITLE
Add vm pool to easily benefit from vm reuse in parallel use-cases

### ISSUE THREAD

**Issue by adam-kiss-sg** [antonmedv/expr#285]
Using go sync.Pool could combine the reuse of vms without the complexity of managing vms in a parallelized use-case.

## VmPool

```
package vm

import (
	"sync"
)

type VMPool struct {
	pool sync.Pool
}

func NewVMPool() *VMPool {
	return &VMPool{
		pool: sync.Pool{
			New: func() interface{} {
				return &VM{}
			},
		},
	}
}

func (vp *VMPool) Run(program *Program, env interface{}) (out interface{}, err error) {
	vm := vp.pool.Get().(*VM)
	defer vp.pool.Put(vm)

	return vm.Run(program, env)
}
```

## Reasoning

Even thought this functionality could be easily added by the user of the lib, having it inside the lib would have some benefits:
- there is minimal amount of code required (see above), so it wouldn't be hard to maintain it
- benchmarking can be provided in the lib, so users can decide which option to pick
- having it in the lib would help people be aware of this option

**Comment by roqenrox** [comment]
I'm not a fan of offering package-side pools that can be easily implemented with standard library. Chances are high that this straight-forward implementation is too simple for many use cases, e.g. because the pool size should be limited. I'd prefer adding it to a section in the README.

Anyway, `VM` is not optimized for pooling: allocated resources are released only with the next call to `Run` and not already with the release into the pool.

Do you think we optimize this before introducing `VMPool`, e.g. by adding a `Reset` function?

**Comment by antonmedv** [comment]
I agree with @roqenrox. It’s easy to add pool.  Expr already supports reuse vm. 

If you want to work on improving efficiency, try to combine OpFetchField and OmMethod into singe OpMethod my adding field *Field to Method. ;)

**Comment by roqenrox** [comment]
> > Moreover, VM is not optimized for pooling: allocated resources are released only with the next call to Run and not already with the release into the pool.
>
> I don't think that's a major issue, maybe the memory usage will be slightly more temporarily, but sync pool grows and shrinks automatically, so the unused vms won't stay there for long.

I thought of [this line](https://github.com/antonmedv/expr/blob/497c6bd01cf837ecda6a2644e5e1868a26fabd9f/vm/vm.go#L66) and, analogously, [that line](https://github.com/antonmedv/expr/blob/master/vm/vm.go#L72), which both support my statement. It's not a matter of `VMPool` but rather of `VM`. Anyway, if that's an issue at all, we should discuss it separately.

**Comment by antonmedv** [comment]
As it really easy to do on user side, closing.
