### ISSUE TITLE
Ability to pass custom Func to CallNode 

### ISSUE THREAD

**Issue by Dentrax** [antonmedv/expr#287]
Carry: https://github.com/antonmedv/expr/issues/277

**Motivation**

In the current implementation, you can not pass a function to CallNode directly. It’s the only option to pass a func from env; which you need to set `Callee` field.

**Use Case**

```golang
divFn := func(left, right float64) float64 {
	if right == 0 {
		panic("integer divide by zero")
	}
	return left / right
}

ast.Patch(node, &ast.CallNode{
	Func:    divFn,
	Arguments: []ast.Node{n.Left, n.Right},
})
```

**Comment by antonmedv** [comment]
Done! Now CallNode have a Func field.
