### ISSUE TITLE
Field keys that contain "dot" does not evaluate correctly with helper functions

### ISSUE THREAD

**Issue by Dentrax** [antonmedv/expr#288]
Example:

```golang
package main

import (
	"fmt"
	"strconv"

	"github.com/antonmedv/expr"
)

func main() {
	env := map[string]interface{}{
		"foo":     "1",
		"bar.baz": "2",
		"ToInt":   ToInt,
	}

	cases := []string{
		"ToInt(foo) == 1",
		"ToInt(\"bar.baz\") == 2",
	}

	for _, c := range cases {
		program, err := expr.Compile(c, expr.Env(env))
		if err != nil {
			panic(err)
		}

		output, err := expr.Run(program, env)
		if err != nil {
			panic(err)
		}

		fmt.Println(output)
	}
}

var ToInt = func(s string) any {
	v, err := strconv.Atoi(s)
	if err != nil {
		panic(err)
	}
	return v
}
```

* `ToInt(foo) == 1` works as expected
* `ToInt(\"bar.baz\") == 2` does not work (`true` is expected in this case)

Resulting:
```
true
panic: strconv.Atoi: parsing "bar.baz": invalid syntax (1:1)
 | ToInt("bar.baz") == 2
 | ^
```

Tag: `v1.9.1-0.20221112134005-497c6bd01cf8`

**Comment by antonmedv** [comment]
Looks like correct behavior to me. 
 `ToInt("bar.baz") == 2` => `strconv.Atoi("bar.baz")` => `parsing "bar.baz": invalid syntax`

Right now it's impossible to get var with a dot in its top level.

See https://go.dev/play/p/mxPMAmaO5hI and #106

**Comment by Dentrax** [comment]
Thanks! How can extend your example snippet to add _string to int_ parsing function?
