### ISSUE TITLE
1.10 change in behavior

### ISSUE THREAD

**Issue by zachaller** [antonmedv/expr#310]
We use this in argo-rollouts code base and when we dependabot upgraded use to 1.10 we now have our unit tests failing with this error

```
interface conversion: interface {} is func(interface {}) float64, not func(string) float64
```

I have done a little bit of digging and it seems like this [file](https://github.com/antonmedv/expr/blob/master/vm/func_types/main.go) got added which defines a set of functions. This seems to break our env which we have defined [here](https://github.com/antonmedv/expr/blob/master/vm/func_types/main.go) I think because it is missing the type of functions we have passed in such as [asFloat](https://github.com/argoproj/argo-rollouts/blob/master/utils/evaluate/evaluate.go#L138)

**Comment by antonmedv** [comment]
I see. Will try to fix this bug.

**Comment by zachaller** [comment]
@antonmedv awesome glad it is a bug, and thank you for the great library :D

**Comment by antonmedv** [comment]
@zachaller will try to fix it over the weekend.

**Comment by antonmedv** [comment]
I need little bit more info, as this code works as expected: 

* https://go.dev/play/p/ndMzR1MNFNA


```go
package main

import (
	"fmt"
	"reflect"
	"strconv"

	"github.com/antonmedv/expr"
)

func main() {
	env := map[string]interface{}{
		"int8":    int8(1),
		"asFloat": asFloat,
	}
	code := `asFloat(int8)`

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%T(%v)", output, output)
}

func asFloat(in interface{}) float64 {
	switch i := in.(type) {
	case float64:
		return i
	case float32:
		return float64(i)
	case int64:
		return float64(i)
	case int32:
		return float64(i)
	case int16:
		return float64(i)
	case int8:
		return float64(i)
	case int:
		return float64(i)
	case uint64:
		return float64(i)
	case uint32:
		return float64(i)
	case uint16:
		return float64(i)
	case uint8:
		return float64(i)
	case uint:
		return float64(i)
	case string:
		inAsFloat, err := strconv.ParseFloat(i, 64)
		if err == nil {
			return inAsFloat
		}
		panic(err)
	}
	panic(fmt.Sprintf("asFloat() not supported on %v %v", reflect.TypeOf(in), in))
}
```

Can you create an example with error? Thanks.

**Comment by roqenrox** [comment]
The error occurs when converting a string to float using `asFloat`: https://go.dev/play/p/6BG_QVOfdz6

**Comment by antonmedv** [comment]
Ok, thanks. This is a regression test:
```go
	env := map[string]interface{}{
		"str":     "8",
		"asFloat": asFloat,
	}
	code := `asFloat(str)`

	program, err := expr.Compile(code, expr.Env(env))
	assert.NoError(t, err)

	out, err := expr.Run(program, env)
	assert.NoError(t, err)
	assert.Equal(t, float64(1), out)
```

**Comment by antonmedv** [comment]
Fixed in 9009d4da3de69a1e5dcbb284a9140129939de6f1  Will release a new version.

**Comment by antonmedv** [comment]
https://github.com/antonmedv/expr/releases/tag/v1.10.1

**Comment by zachaller** [comment]
Awesome thank you for the super quick turnaround!

**Comment by vincentbernat** [comment]
I have another one:

```
interface conversion: interface {} is core.classifyStringFunc, not func(string) bool (1:1)
```

However, I have:

```go
type classifyStringFunc func(string) bool
```

I can work around the issue with

```go
type classifyStringFunc = func(string) bool
```

Maybe do you prefer another issue?

**Comment by antonmedv** [comment]
> Maybe do you prefer another issue?

Yes, please.
