### ISSUE TITLE
misunderstanding of basic functionality

### ISSUE THREAD

**Issue by thrisp** [antonmedv/expr#32]
I'm trying to learn to use this package but struggling to understand some basics

A very basic example extracted from custom code I attempted 
```
env := map[string]interface{}{
    "distance":"far,
}

expr.Eval("distance==far", env)
```
You get an error to the effect of "env doesn't contain far"

This is a reduction of what I attempted which has something like

```
type Attr []byte 

type Task struct {
    v map[string]Attr
}
``` 
where I pass in an expression e.g. "distance==far" to an env of map[string]Attr where I ended up with a swamp of my own code parsing the expression passed in to convert to methods that were unwieldy to work with or not working at all (methods on struct error if they take an interface{}) and still couldn't get it to work as I expected. I am not attempting to be aggressive/accusatory here I sort of just need clarification and pointed to more documentation/examples to find out why I cannot accomplish what I want to accomplish. I might not understand what is going on here and have the wrong package for my use case.

The point being, what is the point? I thought this package was supposed to relate arbitrary expressions to arbitrary data structures, and I have to write a whole other package of parsing and supplementary methods, I might as well start from scratch and do it myself.

**Comment by antonmedv** [comment]
Please provide full code example. 

Also I’m working on my better documentation in the moment.
