### ISSUE TITLE
Can't use in operator with an undefined variable 

### ISSUE THREAD

**Issue by g-ki** [antonmedv/expr#322]
After updating to 1.10 the **in** operator fails to compile when the right operand is undefined.

`invalid operation: in (mismatched types string and interface {})`

Example:
```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
)

func main() {
	code := `'Tom' in names`

	program, err := expr.Compile(code, expr.AllowUndefinedVariables())
	if err != nil {
		panic(err)
	}

	env := map[string]interface{}{
		"names": []string{"Alice", "Bob"},
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}
```

[Go Playground](https://go.dev/play/p/bxpu9rJteQ7)

**Comment by antonmedv** [comment]
Fixed in c59a3b9, release v1.10.5

Please, add Uber to ["Who uses Expr?"](https://github.com/antonmedv/expr#who-uses-expr) section in README.md. 😁
