### ISSUE TITLE
Inconsistent behavior when accessing a field that doesn't exist in env

### ISSUE THREAD

**Issue by jiachengxu** [antonmedv/expr#330]
Hi,
I am trying to use a field which doesn't exist in `env` in both a ternary operator and a simple expression, and I noticed that the behavior is inconsistent:
```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
)

func main() {
	env := map[string]interface{}{
		"foo": map[string]interface{}{
			"fox": 1, // <- Note: here is "fox" not "foo"
		},
		"bar": 2,
	}

	out, err := expr.Eval(`foo.foo == 1 ? "Yes" : "No"`, env) // <- Trying to access "foo.foo" which doesn't exist
	if err != nil {
		panic(err)
	}
	out2, err := expr.Eval(`foo.foo`, env) // <- Trying to access "foo.foo" which doesn't exist
	if err != nil {
		panic(err)
	}
	fmt.Print(out) // No
	fmt.Print(out2) // <nil>
}
```
I think returning `nil` is expected since the field doesn't exist. However, the ternary example returns `No` and it is evaluated. 
Is this by design? Is it possible to not evaluate the expression if the field is not found?

Thanks!

**Comment by scorpinxia** [comment]
I have same issue

**Comment by antonmedv** [comment]
This is how maps are working in Go. [Zero values](https://go.dev/tour/basics/12).

`foo.foo` is nil. This is expected.

So the next expression 

```
foo.foo == 1 ? "Yes" : "No"
```

 became 

```
nil == 1 ? "Yes" : "No"
```

`nil == 1` is false, so

```
false ? "Yes" : "No"
```

Result is `No`.

If you want the types to be more strict - use structs. 

```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
)

type MyType struct {
	Fox int `expr:"fox"`
}

func main() {
	env := map[string]interface{}{
		"foo": MyType{Fox: 1},
		"bar": 2,
	}

	out, err := expr.Eval(`foo.foo == 1 ? "Yes" : "No"`, env)
	if err != nil {
		panic(err)
	}
	fmt.Print(out)
}
```
https://go.dev/play/p/46f2x3VIG-i

**Comment by jiachengxu** [comment]
I see. Thank you!

**Comment by antonmedv** [comment]
Another thing we are working to add to Expr is nil checks. 
 
With nil checks enabled such expression will error on compile.

**Comment by Cassius0924** [comment]
Is this function currently available?

> Another thing we are working to add to Expr is nil checks.我们正在努力添加到 Expr 中的另一件事是 nil 检查。
> 
> With nil checks enabled such expression will error on compile.启用 nil 检查后，此类表达式将在编译时出错。

**Comment by antonmedv** [comment]
The nil check functionality is in development.
