### ISSUE TITLE
Question about operator overloading

### ISSUE THREAD

**Issue by hesining** [antonmedv/expr#334]
``` go
package main

import (
	"fmt"
	"github.com/antonmedv/expr"
)

func main() {
	cnt := 0
	env := make(map[string]any)
	env["returnfalse"] = func() bool {
		cnt++
		return false
	}

	env["and"] = func(l, r bool) bool {
		return l && r
	}

	options := []expr.Option{
		expr.Env(env),
		expr.Operator("&&", "and"),
	}

	code := `returnfalse() && returnfalse() && returnfalse() && returnfalse()`

	program, err := expr.Compile(code, options...)
	if err != nil {
		return
	}

	_, err = expr.Run(program, env)
	if err != nil {
		return
	}
	fmt.Println(cnt)
}
```

I expect 'cnt' equal 2 but get 4.
I checked the code and found that if I overload the operator ‘&&’ and it will become a function call, the 'OpJumpIfFalse' will not set any more.
Is this performance as expected？

**Comment by antonmedv** [comment]
Everything works as expected. Expression:

    returnfalse() && returnfalse() && returnfalse() && returnfalse()

into

    and(and(and(returnfalse(), returnfalse()), returnfalse()), returnfalse())
