### ISSUE TITLE
len(nil) panic

### ISSUE THREAD

**Issue by kris-zhang** [antonmedv/expr#336]
execute len(nil) cause panic

go 1.18
go-expr v1.12.0

```go
program, err := expr.Compile(`len(nil)`, exprEnv)
	if err != nil {
		fmt.Println(err)
		return
	}
	rawResult, err := expr.Run(program, env)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(rawResult)
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10118ee08]

goroutine 1 [running]:
github.com/antonmedv/expr.Compile({0x10119516d, 0x8}, {0x14000267f30, 0x1, 0x140000021a0?})

**Comment by antonmedv** [comment]
Fixed in https://github.com/antonmedv/expr/releases/tag/v1.12.1
