### ISSUE TITLE
Parse math.MinInt64 error: invalid integer literal: strconv.ParseInt: parsing "9223372036854775808": value out of range (1:20)

### ISSUE THREAD

**Issue by huangyt39** [antonmedv/expr#337]
I found it will return error when parsing an expression that contains min int64.
For example expression: "-9223372036854775808 > 0".

Here is the unit test of bad case: 
path: /expr/parser/parser_test.go

```
func TestParseMinInt64(t *testing.T) {
	parseTests := []struct {
		input    string
		expected Node
	}{
		{
			"-9223372036854775808 > 0", // strconv.FormatInt(math.MinInt64, 10),
			&IdentifierNode{Value: "-9223372036854775808"},
		},
	}
	for _, test := range parseTests {
		actual, err := parser.Parse(test.input)
		if err != nil {
			t.Errorf("%s:\n%v", test.input, err)
			continue
		}
		assert.Equal(t, Dump(test.expected), Dump(actual.Node), test.input)
	}
}

```

Result: 
```

=== RUN   TestParseMinInt64
    parser_test.go:471: -9223372036854775808:
        invalid integer literal: strconv.ParseInt: parsing "9223372036854775808": value out of range (1:20)
         | -9223372036854775808
         | ...................^
--- FAIL: TestParseMinInt64 (0.00s)

```

Is it an uncommon bug or just because of my wrong way to use it?

**Comment by antonmedv** [comment]
Hmm, looks like a bug.

**Comment by antonmedv** [comment]
Actually this is not a bug, this is how our expressions are working.

The `-9223372036854775808` parsed as 

```
Unary(-Integer("9223372036854775808"))
```

And strconv.ParseInt will error, as 922337203685477580**8** is overflow.

```
number, err := strconv.ParseInt("9223372036854775808", 10, 64)
```

(see https://go.dev/play/p/-KAP1SVivid)

But with 922337203685477580**7** it works as it is proper math.MaxInt: https://expr.medv.io/playground?code=-9223372036854775807%20%3E%200

**Comment by huangyt39** [comment]
Thanks for your explanation.
It just make me feel weird about returning error when parsing an int64. Maybe this return will be more reasonable:
```
IntegerNode{Value: -9223372036854775808}
```

But since this case doesn't come up very often, I can accept that.

**Comment by antonmedv** [comment]
It’s possible to make it this way. But will require some work. Better to spend the time on adding more impactful features.
