### ISSUE TITLE
invalid char escape

### ISSUE THREAD

**Issue by KoalaInTree** [antonmedv/expr#343]
expr: `trace_content matches '\['`
env：contextMap["trace_content"] = "[8848]"
parse err,err msg:invalid char escape
Snippet:
 | trace_content matches '\['
 | .........................^

**Comment by antonmedv** [comment]
Try to use ‘\\[‘.

**Comment by xFurther** [comment]
why ??
code := `(client_id in ["设备名称: asus sdrw-08u9m-u usb device pid:  vid:  实例路径: usbstor\cdrom&ven_asus&prod_sm-u&rev_a101\k0ekcl04336_________&0"])`

env := make(map[string]interface{})
env["client_id"] = "1667399"
env["client_meta_name"] = "nc06"

prj, err := expr.Compile(code, expr.Env(env), expr.AsBool())
if err != nil {
    panic(err)
}


panic: invalid char escape (1:78)
 | (client_id in ["设备名称: asus sdrw-08u9m-u usb device pid:  vid:  实例路径: usbstor\cdrom&ven_asus&prod_sm-u&rev_a101\k0ekcl04336_________&0"]) [recovered]
	panic: invalid char escape (1:78)
 | (client_id in ["设备名称: asus sdrw-08u9m-u usb device pid:  vid:  实例路径: usbstor\cdrom&ven_asus&prod_sm-u&rev_a101\k0ekcl04336_________&0"])
