### ISSUE TITLE
up to 1.20 and Hold business error 

### ISSUE THREAD

**Issue by hesining** [antonmedv/expr#345]
I find that my own error information of method and function turned to string, and I can't use it conveniently. The go 1.20 has the new function 'errors.Join' and I think the expr code about recover can modify like this 

``` go
func (vm *VM) Run(program *Program, env interface{}) (_ interface{}, err error) {
	defer func() {
		if r := recover(); r != nil {
			f := &file.Error{
				Location: program.Locations[vm.ip-1],
			}

			var ok bool
			if err, ok = r.(error); !ok {
				f.Message = fmt.Sprintf("%v", r)
				err = f.Bind(program.Source)
			} else {
				err = errors.Join(err, f.Bind(program.Source))
			}
		}
	}()
//...
}
```

How about up to 1.20 and use the new feature ?

**Comment by antonmedv** [comment]
Currently some users of Expr still use go1.13. We have unit tests there too.


One way to get your own errors back: save errors in env struct’s field.

**Comment by hesining** [comment]
> Currently some users of Expr still use go1.13. We have unit tests there too.
> 
> One way to get your own errors back: save errors in env struct’s field.

Yes, It's a way.  save it in env struct’s field instead of return it. The only problem is that users should change  their writing habits.

**Comment by GeraldXv** [comment]
I also encountered a similar problem.

**Comment by antonmedv** [comment]
What about adding WrappedError fields to file.Error?

**Comment by hesining** [comment]
> What about adding WrappedError fields to file.Error?

it's a good idea. I'll try it later.

**Comment by hesining** [comment]
https://github.com/antonmedv/expr/pull/352
@antonmedv  I try it , please check it.

**Comment by antonmedv** [comment]
Released!
