### ISSUE TITLE
ast.IndexNode and ast.MethodNode undefined

### ISSUE THREAD

**Issue by ernest-ag5** [antonmedv/expr#361]
when upgrading frrom v1.9.0 to v1.12.1 I noticed that these two types are no longer present. This is a breaking change assuming that both types are intended to be part of the public interface.

What is the new alternative to extend the package by patching nodes?

Here is my use case: https://github.com/emicklei/melrose/blob/master/dsl/environment_map.go

**Comment by antonmedv** [comment]
```diff
-func (p *indexedAccessPatcher) Exit(node *ast.Node) {
+func (p *indexedAccessPatcher) Visit(node *ast.Node) {
```

**Comment by antonmedv** [comment]
Now it’s one unified MemberNode
