### ISSUE TITLE
Some builtins may wrongly compile

### ISSUE THREAD

**Issue by Xelemsta** [antonmedv/expr#365]
Hi,

Given this reproducer: 

https://go.dev/play/p/jDfUjjd9173

I was wondering if we should expect that `len` as strict expression should compile or not. I believe all other builtins (abs, float, ...) are also concerned. Before 1.11.0 version, compiling this expression returns an error.

Let me know if you need more input.

**Comment by antonmedv** [comment]
Looks like right now `len` expression fails:
```
error while compiling foo: unknown name Foo (1:1)
 | Foo
 | ^ 
len compiled
error while running: cannot fetch len from main.Env (1:1)
 | len
 | ^ 
```
