### ISSUE TITLE
Patcher example with IndexNode no longer works

### ISSUE THREAD

**Issue by mdmcconnell** [antonmedv/expr#366]
New here, please be gentle.  I think the first Patcher example at https://expr.medv.io/docs/Visitor-and-Patch is no longer working since the IndexNode type went away last October.  I'm not certain how to update the code to restore functionality - looks like check Method, then alter MethodIndex?  But is a check for UnaryNode still relevant?  The examples have been very helpful for me in starting to work with expr.

**Comment by antonmedv** [comment]
Yes, looks like the examples are outdated. I need to fix the documentation.

**Comment by antonmedv** [comment]
Updated documentation https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md#patch
