### ISSUE TITLE
RunWithContext

### ISSUE THREAD

**Issue by thomascoquet** [antonmedv/expr#380]
Hello,

Would you be interested / ok with a PR adding a `RunWithContext` method?

Like functions returning `(any, error)`, `expr` could also accept functions with arguments `(context.Context, ...)`.

Thanks, Thomas

**Comment by antonmedv** [comment]
Let's try to create the PR and discuss it there.

**Comment by antonmedv** [comment]
FYI. I've implemented my own version of context patcher and added a config option https://github.com/antonmedv/expr/blob/f92bb7949de064a05d5b3a61d1b07abef0c521bb/expr.go#L157-L161

```go
func ExampleWithContext() {
	env := map[string]any{
		"fn": func(ctx context.Context, _, _ int) int {
			// An infinite loop that can be canceled by context.
			for {
				select {
				case <-ctx.Done():
					return 42
				}
			}
		},
		"ctx": context.TODO(), // Context should be passed as a variable.
	}

	program, err := expr.Compile(`fn(1, 2)`,
		expr.Env(env),
		expr.WithContext("ctx"), // Pass context variable name.
	)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}

	// Cancel context after 100 milliseconds.
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond*100)
	defer cancel()

	// After program is compiled, context can be passed to Run.
	env["ctx"] = ctx

	// Run will return 42 after 100 milliseconds.
	output, err := expr.Run(program, env)
	if err != nil {
		fmt.Printf("%v", err)
		return
	}

	fmt.Printf("%v", output)
	// Output: 42
}
```

**Comment by thomascoquet** [comment]
Thank you for the update! I had used meanwhile my own AST patcher, but this was indeed quite limited as one needed to know in advance if the function accepts or not a context as first argument.
