### ISSUE TITLE
configurable argument character in predicate

### ISSUE THREAD

**Issue by marcelvanwaaijen** [antonmedv/expr#384]
Hi,

To access the argument in a predicate, I should use the '#' character, but I want to use the expression in an ini file, where the '#' character marks the start of a comment... 

Is it possible to make this character configurable, so I can use '$' for instance instead of '#'?

Thanks,
Marcel.

**Comment by antonmedv** [comment]
I think it is possible to add this configuration logic. But I am afraid it will complicate things a lot. 

Also, I think to reuse $ soon for accessing parts of matched expressions. `foo matches "foo(.+)" ? $1 : "no foo"`

**Comment by marcelvanwaaijen** [comment]
The dollar sign was just an example, it would be nice if you could specify any character you like as the argument placeholder through an option, but if it is too complicated, then leave it. I already found a workaround for my case using ini files in viper.

Thanks,
