### ISSUE TITLE
FQ: not in contains

### ISSUE THREAD

**Issue by KyleSanderson** [antonmedv/expr#388]
First of all, thank you very much for this library. It was very easy to get going, and I already have tens of users (which, I find a bit humorous, but I digress).

One thing we're struggling with is to keep the complexity of the expressions down, and we're looking to use contains for wildcarding with an array to keep it nice and clean. We're using the in clause for absolute expressions, however expanding contains to in would promote that syntax greatly as opposed to the present forced boolean logic. Finally negating the clause entirely is also highly desirable for filtering down results.

Hopefully that made some sense, if not I'm happy to add additional colour.

**Comment by antonmedv** [comment]
Hi, please show an example of the expression  


What about using all() predicates?

**Comment by KyleSanderson** [comment]
it still doesn't seem possible at this time.

`name not in startsWith [ "cats", "dogs", "james" ]`

nice new built-ins btw, replaces some but not all of my stuff.

**Comment by antonmedv** [comment]
[ "cats", "dogs", "james" ] | all(name not startsWith #)

You can use this instead.

**Comment by KyleSanderson** [comment]
nice! thank you very much
