### ISSUE TITLE
FQ: type operator

### ISSUE THREAD

**Issue by KyleSanderson** [antonmedv/expr#389]
hello, thank you very much for this library. I have a collection of custom types I can't seem to add operators for. The language just errors out, so to expose or compare two types together (a cast string in golang, to a string in the expr) I'm forced to convert to a basic type.

What I'm envisioning is something like expr.Operator(type1, type2, 'token', func(token string, type1, type2) bool)).

**Comment by antonmedv** [comment]
It is possible, see https://expr.medv.io/docs/Operator-Overloading

**Comment by KyleSanderson** [comment]
I'm under the impression you can only have a single Env. Maybe I've done the wrong thing? 

https://github.com/KyleSanderson/upgraderr/blob/eb57691c62b3c58f3de475d086d38c72f6a757e4/main.go#L1300

**Comment by antonmedv** [comment]
It should work with operators overloading.

**Comment by KyleSanderson** [comment]
> It should work with operators overloading.

I guess the confusion here is that overloads the operator for everything, no? There's like 30 types that I don't want to change it for, and want to target the custom types instead.

**Comment by antonmedv** [comment]
Only for custom types you define.
