### ISSUE TITLE
How to get nil if occur unknown name error。

### ISSUE THREAD

**Issue by techbobo** [antonmedv/expr#39]

**Comment by antonmedv** [comment]
Can you show me an example?

**Comment by antonmedv** [comment]
I found an error, what you cannot compare to nil. Will fix it.

**Comment by techbobo** [comment]
![image](https://user-images.githubusercontent.com/10804198/60963165-98e7ae00-a342-11e9-8f7b-4f8b82bb7d72.png)

This is correct because of parameter A.

![image](https://user-images.githubusercontent.com/10804198/60963232-d1878780-a342-11e9-9575-7c4cf9c34940.png)

This is wrong because the C parameter is not found, but I want the result: nil。
I don't want the execution of the terminal program. If I can't find the parameters, I use nil to compare with other parameters and finally get an execution result.

**Comment by antonmedv** [comment]
Okay, I see. The whole point of `expr.Env` option is to define everything on compile time. The simplest solution is to omit Env param or pass nil there. 
But if you want to partially check variables, but be able to use undefined variables, I think we can use something like `expr.AllowUnknownVariables()` option.

Also, take a look at this commit: 85ffe5789329ee006f0fb30b4d18a1d42fe8c924
There is an example with undefined variables.

**Comment by techbobo** [comment]
Thank you very much, great！！！
