### ISSUE TITLE
Adding builtin sort function

### ISSUE THREAD

**Issue by wvell** [antonmedv/expr#395]
I have a use case where i want to be able to sort a slice based on a predicate. Something like this:
```
sort(Tweets, { a.Len < b.Len })
```

The usecase for me is sorting by price and fetching the first x items. I can try to implement this, would you like to see this as a built in?

**Comment by antonmedv** [comment]
This is a nice idea, I'm also thinking about adding sort and reduce functions. Right now predicates takes only one arg via `#` symbol. I think something like in Kotlin will be cool.

```
sort(Tweets, #1.Len < #2.Len)
```

**Comment by wvell** [comment]
I tried looking into it but also got stuck in the opcodes. Thank you! I will test it.
