### ISSUE TITLE
panic in MemberNode func

### ISSUE THREAD

**Issue by s6816112** [antonmedv/expr#396]
version: v1.12.5
expr:  $params_announce_type != nil ? 2: 1
when $params_announce_type value is nil 

`	base, _ := v.visit(node.Node) // base is nil
	prop, _ := v.visit(node.Property)

	if name, ok := node.Property.(*ast.StringNode); ok {
		if base == nil {
			return v.error(node, "type %v has no field %v", base, name.Value)
		}
		// First, check methods defined on base type itself,
		// independent of which type it is. Without dereferencing.
		if m, ok := base.MethodByName(name.Value); ok {
			*****
		}
	}

	if base.Kind() == reflect.Ptr { //  **panic in this line**
		base = base.Elem()
	}
`
why not  move `if base == nil`  in here 
`	base, _ := v.visit(node.Node) // base is nil
	prop, _ := v.visit(node.Property)

        if base == nil {
			return v.error(node, "type %v has no field %v", base, name.Value)
	}
	if name, ok := node.Property.(*ast.StringNode); ok {
		******
	}

	if base.Kind() == reflect.Ptr { //  **panic in this line**
		base = base.Elem()
	}
`

**Comment by antonmedv** [comment]
Works for me:
```go
func TestEval(t *testing.T) {
	output, err := expr.Eval("foo == nil ? true : false", map[string]interface{}{"foo": nil})
	require.NoError(t, err)

	assert.Equal(t, true, output)
}
```
