### ISSUE TITLE
Why Fetcher interface removed?

### ISSUE THREAD

**Issue by re-dylan** [antonmedv/expr#404]
For v1.9.0 ,  has a define Fetcher interface. Unexported fields cannot be accessed by Fetcher.
But why removed this feature?

```go
type Fetcher interface {
	Fetch(interface{}) interface{}
}
```

link: https://github.com/antonmedv/expr/issues/204

**Comment by re-dylan** [comment]
I got a demo, How cloud it work for patch?

```go
package main

import (
	"fmt"

	"github.com/antonmedv/expr"
)

type User struct {
	Name string
	age  int64
}

func (u *User) Fetch(i any) any {
	var string_i string
	if s, ok := i.(string); ok {
		string_i = s
	} else {
		string_i = fmt.Sprint(i)
	}
	switch string_i {
	case "Name":
		return u.Name
	case "age":
		return u.age
	}
	return nil
}

func main() {
	u := &User{
		Name: "dylan",
		age:  10,
	}
	resp, err := expr.Eval(`u.age`, map[string]any{
		"u": u,
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(resp)
}
```

**Comment by re-dylan** [comment]
By the way, I think expr shouldn't make big break change.
When I upgrade expr version,  my old script won't work ok.

**Comment by antonmedv** [comment]
Use patcher to replace u.age by u.Fetch(‘age’)

**Comment by Elvins** [comment]
> Fetcher interface was removed as it was replaced by a faster interface of accessing fields of structs.
> 
> If still want Fetcher interface, ,you can use https://github.com/antonmedv/expr/blob/master/docs/Visitor-and-Patch.md#patch feature.

a faster interface of accessing fields of structs is ?

**Comment by antonmedv** [comment]
Yes, now Expr uses special predefined signatures for functions and effectively utilises reflect for struct accesses.

**Comment by antonmedv** [comment]
You can still get “Fetcher”-style behavior by using the `expr.Patch` hook to rewrite every unexported-field access into a call to your type’s `Fetch` method before the expression is compiled. In outline:

1. **Define your type and its `Fetch` method**

   ```go
   type User struct {
     Name string
     age  int64
   }

   // Fetch implements the old Fetcher interface:
   func (u *User) Fetch(field any) any {
     if name, ok := field.(string); ok {
       switch name {
       case "Name":
         return u.Name
       case "age":
         return u.age
       }
     }
     return nil
   }
   ```
2. **Write a patcher that rewrites `u.age` → `u.Fetch("age")`**

   ```go
   import (
     "github.com/antonmedv/expr"
     "github.com/antonmedv/expr/ast"
   )

   // fetcherPatcher will turn every MemberNode into a Fetch call.
   type fetcherPatcher struct{}

   func (p fetcherPatcher) Visit(node *ast.Node) {
     sel, ok := (*node).(*ast.MemberNode) // AST node for “x.y”
     if !ok {
       return
     }
     // rebuild it as a call to x.Fetch("y")
     call := &ast.CallNode{
       Callee: &ast.MemberNode{
         Node:     sel.Node,
         Property: "Fetch",
       },
       Arguments: []ast.Node{
         &ast.StringNode{Value: sel.Property},
       },
     }
     ast.Patch(node, call)
   }
   ```
3. **Compile and run with your patcher**

   ```go
   func main() {
     u := &User{Name: "dylan", age: 10}

      env := map[string]interface{}{"u": u}

     // Compile with our patcher
     program, err := expr.Compile(
       `u.age`,                                  // note: age is unexported
       expr.Env(env),
       expr.Patch(fetcherPatcher{}),            // inject our transformation
     )
     if err != nil {
       panic(err)
     }

     // Now running will invoke u.Fetch("age") under the hood
     out, err := expr.Run(program, env)
     if err != nil {
       panic(err)
     }
     fmt.Println(out) // → 10
   }
   ```

**Comment by Elvins** [comment]
What if the User object is used for Env? like: 
```golang
func main() {
  u := &User{Name: "dylan", age: 10}
  // Compile with our patcher
  program, err := expr.Compile(
    `age == 10`,                                  // note: age is unexported
    expr.Env(u),
    expr.Patch(fetcherPatcher{}),            // inject our transformation
  )
 ...
```

**Comment by Elvins** [comment]
the type of ast.CallNode.Callee is also ast.IdentifierNode, so how does the implementation of Patch exclude this situation?

**Comment by antonmedv** [comment]
Your patcher needs to understand if those calls should be avoided.

**Comment by Elvins** [comment]
but there are no way to understand.

<img width="512" alt="Image" src="https://github.com/user-attachments/assets/f21c64fc-8eb0-48bf-a232-b33fde9d6516" />

**Comment by antonmedv** [comment]
I see. But you can check the name of IdentifierNode. If it is `Fetch`, then no need to replace it.
