### ISSUE TITLE
Negative slice index out of bounds

### ISSUE THREAD

**Issue by fmarcia** [antonmedv/expr#406]
If `test == "abc"`, `test[4:]` returns an empty string but `test[-4:]` raises an error:
```
error: reflect.Value.Slice: string slice index out of bounds (1:5)
 | test[-4:]
 | ....^
```
Python returns `'abc'`.
I'm opening this issue because of [one of your comments](https://github.com/antonmedv/expr/issues/341#issuecomment-1466626603).

**Comment by antonmedv** [comment]
Will fix it.

**Comment by antonmedv** [comment]
Fixed!
