### ISSUE TITLE
Assignment support

### ISSUE THREAD

**Issue by alok87** [antonmedv/expr#407]
## What?
Need assignment support to add Then execution support in rules.

Our rule definition is this
```go

type RuleDefination struct {
	// When is the expression that needs to be checked
	// it can contain logical operations between facts
	// Order.Amount > 500 && Customer.Segment = new
	When string
	// Then is expressions that are evaluated when when satisfies
        // Discount.Amount = 500
	Then string
	Salience int
}
```

We wanted to use Expr to build the rule execution, getting below error due to assignment support missing.
```
panic: unexpected token Operator("=") (1:14)
 | Discount.Amount = 50
 | .............^

goroutine 1 [running]:
```

Complete code: https://go.dev/play/p/L9O0tNLf9yz

## Support request
Getting above mentioned error, since assignment is not supported at present. Do let me know if you are ok with supporting assignment. If you can guide where all changes are required, I can contribute back here.

**Comment by mdmcconnell** [comment]
Why not do your assignment outside of expr, in go code?  If necessary, you could define expressions for each variable you want to set.

**Comment by alok87** [comment]
It would help us to do it generically on our layer, if we have assignment support here only, then is a very common use case. If you can allow assignment, it would help others as well in the same format. For example this does this but it is very compute heavy https://github.com/hyperjumptech/grule-rule-engine/tree/master#rule-engine-for-go. We were building something similar with simple expr.

Any concerns with adding it here?

**Comment by antonmedv** [comment]
One of the features of Expr is side-effect-free execution. It means the expression can not in any way modify the outer world, Go runtime, and passed variables. I do have plans to add variable creation in Expr. But those variables will be internal to the VM. 

One solution you can use is adding a custom function what can modify state. For example:

```js
(Order.Amount > 500 && Customer.Segment = new) ? set('discount', 50) : set('discount', 0)
```

**Comment by alok87** [comment]
Does custom functions make the executions slow if it has the same assignment operations only?

**Comment by antonmedv** [comment]
Function execution in expr is fast. You can also use https://expr.medv.io/docs/Configuration#function to get most of the API.

**Comment by alok87** [comment]
Thanks if custom functions are fast. This works out best for us too!
