### ISSUE TITLE
conflicts with builtin functions

### ISSUE THREAD

**Issue by emicklei** [antonmedv/expr#410]
Hi,

I have been using expr for quite some time. Currently, I use version v1.12.1
Today, I tried upgrading to v1.14.0 but my tests show conflicts with my custom functions:
- join
- repeat

So, what are my options:
- i stick to version 1.12 forever
- i clone the repo and use a modified version
- can I disable built-in functions?
- can we refactor this package to have pluggable behavior (so I can not include those conflicting function)?

**Comment by antonmedv** [comment]
Hi, 

Yes this is what I was afraid of. At begging I was thinking to allow override builtin functions, but fought it may confuse on what function is executed. 

> can I disable built-in functions

I think this is the best solution. We can introduce a config option to disable a builtin function:


    expr.DisableBuiltin(name string)


Will implement it today.

**Comment by antonmedv** [comment]
Added next functions:
- `DisableAllBuiltins()`
- `DisableBuiltin()`
- `EnableBuiltin()`

**Comment by emicklei** [comment]
thx, will check it
