### ISSUE TITLE
Is that possible to list all supported functions?

### ISSUE THREAD

**Issue by LinuxSuRen** [antonmedv/expr#413]
I'm a maintainer of [an API Testing](https://github.com/LinuxSuRen/api-testing) project. I wish it could provide a way to let users search and choose a suitbale function instead of visting the document. So, I'm wondering if there is a way to list all supported functions.

**Comment by antonmedv** [comment]
You can use `builtin.Names`. It contains most of the available functions.

Only `all`, `none`, `map`, `filter`, `count` and other predicates are missing.

But I'm thinking maybe I should add somehow the full list. 

Also there is [expr/docgen](https://github.com/antonmedv/expr/tree/master/docgen) package.

**Comment by antonmedv** [comment]
Added all builtins to this list in e08a599f6b6f0e75e1f9c7ce796fc0eb03a480c7

**Comment by LinuxSuRen** [comment]
Cool!
