### ISSUE TITLE
support slice to map builtin function?

### ISSUE THREAD

**Issue by forrestlinfeng** [antonmedv/expr#417]
like this:
expr.Run("group(xxx, id)",   xxx)

input:  [
{ "id":  "key1",  "a"：123,  ”b“： ”abc“ }, 
{ "id":  "key2",  "a"：123,  ”b“： ”abc“ }
]
output {
    "key1" : { "id":  "key1",  "a"：123,  ”b“： ”abc“ },
    "key2" : { "id":  "key1",  "a"：123,  ”b“： ”abc“ }
}

**Comment by antonmedv** [comment]
Duplicate of #162
