### ISSUE TITLE
Propagate `uint32` arguments types in ast

### ISSUE THREAD

**Issue by hesining** [antonmedv/expr#432]
``` go

package main

import (
	"fmt"
	"github.com/antonmedv/expr"
)

type Tweet struct {
	Len int
}

type Env struct {
	Tweets []Tweet
}

func (e *Env) IsTestXXX(objID uint32) (rslt bool) {
	fmt.Println(objID)
	return true
}

func main() {
	code := `IsTestXXX(111)`

	env := &Env{
		Tweets: []Tweet{{42}, {98}, {69}},
	}

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	fmt.Println(program.Source.Content())

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}


```

receve error msg 

```
panic: cannot use int as argument (type uint32) to call IsTestXXX  (1:11)
 | IsTestXXX(111)                                                        
 | ..........^    
```

**Comment by antonmedv** [comment]
Right now Expr if it sees `\d+` assumes that it is `int`. If a function takes `float64`, Expr will convert this `int` to `float64` as well. We can add the same logic for other types like `uint32`.

**Comment by hesining** [comment]
> Right now Expr if it sees `\d+` assumes that it is `int`. If a function takes `float64`, Expr will convert this `int` to `float64` as well. We can add the same logic for other types like `uint32`.

OK, I think I can try to fix it , give me some time.

**Comment by hesining** [comment]
https://github.com/antonmedv/expr/pull/436

i fix in here, please check it

**Comment by hesining** [comment]
https://github.com/antonmedv/expr/pull/437

i fix it here, please check the code.

**Comment by hesining** [comment]
@antonmedv 
There are some errors reported by fuzz. Can you help me deal with them? There should be no problem with the code.

**Comment by antonmedv** [comment]
Will take a look

**Comment by hesining** [comment]
> Will take a look

the code passed the verification, please take a look.

**Comment by antonmedv** [comment]
Done https://github.com/antonmedv/expr/releases/tag/v1.15.2
