### ISSUE TITLE
"Not Equal to Nil" kind of check before executing expressions

### ISSUE THREAD

**Issue by alok87** [antonmedv/expr#433]
hey we wrote a simple rule engine using `expr` (with when and then)

Problem:
Our users specify rules like show offers if `order.Amount > 500` and `product.Category = xyz`. But at the time offer discovery sometimes order Amount is not available or sometimes product.Category is also not available. But we want to show the offers to those users. So we want to write an expression like:

```
(order.Amount > 500 || order.Amount == 0) &&
(product.Category == xyz || product.Category == "")  
```

But doing this for every fact fields (facts are order and product here) is adding un-necessary complexity in writing such rules. As users in API just specify conditions around fact's field. Order's and product's fields. And we make an expression from it internally.

Do you have any suggestion around this problem's solution with expr?

**Comment by antonmedv** [comment]
Another check I'm planning to add to expr is nil checks: user will be asked to make sure what avalue is not nil before processing.

    err: order is potentialy nil
    | order.Amount > 500 or product.Category = xyz
    |......^

And users can ckange expression to something like this:

    order != nil ? order.Amount > 500 : true

Or to:

    order?.Amount ?? 999 > 500

**Comment by alok87** [comment]
@antonmedv let me try to tell it from API side of this.

## Offer Creation
Offer is created with expressions like this. At the time of discovery we need to show all offers based on the facts passed at the time of offer discovery, but at the time of availment we need to mandatory require all order and product data to say it can be availed or not.

So at present we have to create offer like this:
```
offer:
    metadata:
    spec:
          eligiblity_rule:
                   discovery_of_offer:
                             (order.amount > 500 || order.amount == 0) &&
                             (product.category == xyz || product.category == "") 
                    availment_of_offer:
                             order.amount > 500 && product.category == xyz
```


## Offer Discovery:
API would be like: GET /eligible_offers
```yaml
facts:
     order: 
        amount: 500
      product:
         category: 200
```
In this API `order` and `product` if passed we should filter the offers for them else not. Hence the || checks in disovery_of_offer rule.

This is also required because at the time of discovery of offers, all facts are not present. So we do not want to filter out those offers for users.

The nil check idea you suggested would help.

**Comment by antonmedv** [comment]
Another thing you can use right now is Patcher. You can modify users requests and add corresponding || automatically.

**Comment by alok87** [comment]
What is Patcher? 
We were thinking of doing that after getting API request to convert it into expressions with `||`, but we have to do that for every field of every object.

**Comment by antonmedv** [comment]
https://expr.medv.io/docs/Visitor-and-Patch

**Comment by alok87** [comment]
@antonmedv thanks, let us check this.

**Comment by alok87** [comment]
@antonmedv we want clients only to do own the logic of writing the expressions and not want to manipulate it with patch. Nil check would help us.

**Comment by antonmedv** [comment]
Another thing is how you unmarshal things. For example what to do if order not present.
