### ISSUE TITLE
Playground error on unsupported type: map[interface {}]interface {}

### ISSUE THREAD

**Issue by yoavj-arpeely** [antonmedv/expr#449]
The following expression raises an error on the playground:
```[["some_key", 42]] | map(fromPairs([["key", #[0]], ["val",#[1]]]))```
output:
```json: unsupported type: map[interface {}]interface {}```

However, I believe the problem is not with the expression itself, as the following one does work:

```[["some_key", 42]] | map(fromPairs([["key", #[0]], ["val",#[1]]])) | map(.key)```
output:
```
[
  "some_key"
]
```

**Comment by antonmedv** [comment]
Yes, playground can not stringify map[any]any to json. As for json only string keys are allowed.
