### ISSUE TITLE
Should expr support `+n%` syntax?

### ISSUE THREAD

**Issue by antonmedv** [antonmedv/expr#45]
## `100*1.05` vs `100+5%`

I'm thinking about adding this `+n%` syntax to expr library. What do you think about it? Please share your opinion. 

Expr has already `%` sign as mod: `42 % 5 == 2`. But new syntax can be ambiguous. To deal with it it will be handled on the parse phase and allowed only in `A+N%` and `A-N%` constructions. 

Expr language is also made for people without programming background and for them, it will be more easy to deal with such syntax:
 
* `111 * (1 - 0.11)` vs `111 - 11%`

Please, share your opinion.

**Comment by Ahnfelt** [comment]
I think the `x + y%` syntax just confuses things - would it be equal to `x + 1 * y%`? What's `x + 10% + 10%`? Is it different from `x + (10% + 10%)`? Is `+` no longer associative? Is `1` no longer the identity element for `*`?

**Comment by mamcx** [comment]
I like this. How deal with ambiguity? Pick one and be consistent. Nobody know what associativity is EXCEPT AS TEACHED:

https://plus.maths.org/content/pemdas-paradox

What we have today is just because somebody pick a side and everyone else follow. That is.

**Comment by varonaPTX** [comment]
I'll agree the second is too ambiguous.  What is 100 + 50 + 5%?  5% has to be 5% _of something._  Is it only the closest value?  The whole thing?

I don't think there'd be a problem if you chose a reliable pattern in each case, but to me 100 + 50 + 5% is ambiguous to the reader, even if the code knows what to do.  I'd recommend avoiding by not allowing it, or requiring a clearer syntax like "100 + (50+5%)" and making the other format illegal.

**Comment by Ahnfelt** [comment]
@mamcx Associativity as in the property that `a + (b + c) = (a + b) + c`. Not left/right-associative or operator precedence.

**Comment by TZubiri** [comment]
I personally dislike the widespread use of percentages, they are a starter tool that allows multiplication by decimal factors without actually using decimals, good for supermarkets and primary school, but people need a nudge to graduate from them.

I'd like to see a syntax error on 100 + 5%, since the true mathematical operation that the user expects is actually a multiplication. The syntax error should guide the user towards 100*5%, and the parser should simply translate 5% to 0.05 

This nice compromise would let the user think they are using good old percentages, but is actually showing them the true mathematical nature of them.

**Comment by TZubiri** [comment]
Percentages are ok in primary schools and supermarket offers, they are a way to convey fractional values without actually using fractions or decimal numbers. But they lead to incorrect assumptions like thinking that a multiplication is an addition, that 100 is a multiplicative identity, or that percentages is a fundamental mathematical operation.
If this were my tool, I would graciously guide users with syntax errors and unexpected results to show them the true way.

>>100 + 5%
> 100.05
> Warning: Addition of percentage (percentage operations are typically multiplications, try multiplying a number by a percentage to see an expected result.)
>> 100 * 5%
> 5
>> 100 * 105%
> 105

I have a great deal of respect for opinionated tools that take these kinds of risks. It's easy to give the user what they want, it takes courage to gently tell them they are wrong and improving their minds in the process.

**Comment by antonmedv** [comment]
I decided not to do this.
