### ISSUE TITLE
Int possibly not converted to float on ternary condition

### ISSUE THREAD

**Issue by gauron99** [antonmedv/expr#454]
Hello, Ive been testing some expressions and ran into this:

## using versions 
```
go 1.20
require github.com/antonmedv/expr v1.15.3
```

## my output (expected this to not return an error on compile)
```
| foo > 2 ? foo + bar : 1 | map[bar:2 baz:3 foo:1] -- err compile
error trying to compile custom formula: expected float64, but got interface {}
```

### explanation of output
some explanation: first there is the expression `foo > 2 ? foo + bar : 1` -> followed by its environment map ` map[bar:2 baz:3 foo:1]` and following `--` is the output. This gives me en error that float was expected as I compiled like this:

## how I compiled
```program, err := expr.Compile(formula, expr.Env(env), expr.AsFloat64())```

## but this works
when i change the expression like this `foo > 2 ? foo + bar : 1.0`  I get 
`| foo > 2 ? foo + bar : 1.0 | map[bar:2 baz:3 foo:1] -- out:1(float64)` meaning I get successfully 1 as expected.

# additional info
It looks like this happens only with the ternary operator as the other expressions give me no problems see below

```
---
| 1+2 | map[] -- out:3(float64)
---
| foo+2 | map[foo:1] -- out:3(float64)
---
| (foo+bar)/2 | map[bar:2 baz:3 foo:1] -- out:1.5(float64)
---
| foo < 2 ? 15 : 20 | map[bar:2 baz:3 foo:1] -- out:15(float64)
---
| foo > 2 && bar > 2 ? 15 : 1 | map[bar:2 baz:3 foo:1] -- out:1(float64)
---
| foo < 2 ? foo+bar > 1 ? 1 : 2 : 3 | map[bar:2 baz:3 foo:1] -- out:1(float64)
---
| count([foo,bar,baz],{#>1}) > 1 ? 5 : 10 | map[bar:2 baz:3 foo:1] -- out:5(float64)
---
| foo > 2 ? foo + bar : 1 | map[bar:2 baz:3 foo:1] -- err compile
error trying to compile custom formula: expected float64, but got interface {}
```

**Comment by antonmedv** [comment]
Yes, as return type of `cond ? x : y` is `any`. Cast to float:

```
    float(cond ? x : y)
```
