### ISSUE TITLE
feature request: json path support

### ISSUE THREAD

**Issue by koladilip** [antonmedv/expr#455]
JSON path support like [gjson](https://github.com/tidwall/gjson) will greatly help. What do you think?

**Comment by antonmedv** [comment]
You can add gjson as an external helper.

**Comment by antonmedv** [comment]
Can you give me an example of the expression? I still think it is possible to do it without modifying Expr and implement your feature using the API provided by Expr.

**Comment by koladilip** [comment]
You are right, we can write gjson expression using filters and maps but there are capabilities that are offered by [jsonata](https://docs.jsonata.org/overview.html) that can't be done on Expr.

But the following things are easy to do with path context variables.
```json
{
  "Account": {
    "Account Name": "Firefly",
    "Order": [
      {
        "OrderID": "order103",
        "Product": [
          {
            "Product Name": "Bowler Hat",
            "ProductID": 858383,
            "Price": 34.45,
            "Quantity": 2
          },
          {
            "Product Name": "Trilby hat",
            "ProductID": 858236,
            "Price": 21.67,
            "Quantity": 1
          }
        ]
      },
      {
        "OrderID": "order104",
        "Product": [
          {
            "Product Name": "Bowler Hat",
            "ProductID": 858383,
            "Price": 34.45,
            "Quantity": 4
          },
          {
            "ProductID": 345664,
            "Product Name": "Cloak",
            "Price": 107.99,
            "Quantity": 1
          }
        ]
      }
    ]
  }
}
```
* Let's say we want to generate a summary of products using order, ProductID, quantity and price then n json template engine, we can do this.
```js
.Account.Order@order.Product@product.({
    orderId: order.OrderID,
    productId: product.ProductID,
    quantity: product.Quantity,
    price: product.Price
})
```
Explanation: `@order` refers to an order in that context almost like an iteration variable which gets assigned new values as we iterate.
Output:
```json
[
  {
    "orderId": "order103",
    "productId": 858383,
    "quantity": 2,
    "price": 34.45
  },
  {
    "orderId": "order103",
    "productId": 858236,
    "quantity": 1,
    "price": 21.67
  },
  {
    "orderId": "order104",
    "productId": 345664,
    "quantity": 1,
    "price": 107.99
  }
]
```
You can try it [here](http://jte-beta.rudderstack.com.s3-website-us-east-1.amazonaws.com/)

![image](https://github.com/antonmedv/expr/assets/33080863/d99ab7fd-47c0-4c77-aa35-84a1e84ed69a)

**Comment by antonmedv** [comment]
I see. And you want something like this in Expr? In what form data is presented?

**Comment by koladilip** [comment]
Do you think it will be useful? Yes, it will help us to adapt `expr` more at our company. I have already added a plugin type based on `expr`. Expr already has a pipe feature in expr I think it works in stages, for example, if one expression in pipe gets executed fully then it will be sent to the next expression, if we can make it like a stream, one data element goes all the way and then next element then we can do more interesting with it. Input data can be struct, map, or array of structs or maps.

**Comment by antonmedv** [comment]
What about defining a custom helper function?

    data | jsonpath('some.json.path')

**Comment by koladilip** [comment]
we can do that but it is no different from using gjson right? if the path can be compiled and stored then it will be faster.

**Comment by antonmedv** [comment]
It can be compiled. Check out [expr.ConstExpr](https://expr.medv.io/docs/Configuration#constexpr).

**Comment by koladilip** [comment]
That works with static data but if the data is dynamic then it won't work right?

**Comment by antonmedv** [comment]
I don't understand what do you mean by dynamic data? If your env is `map[string]any` you can still use jsonpath. 

Also, what do you mean about "path to be compile"? 

Please explain more. With some examples of golang and expr code of what do you would like to do.

**Comment by koladilip** [comment]
To extract the data using the path, first we need to parse the path and, then according to the path, we need to extract data, if we parse the path every time then it will not be efficient. For example: in my JsonTemplate library, I generate a javascript code for the path which can generically handle different types of data. In Expr, you are generating ByteCode and then using it you are running on given data so my question is, how can we generate bytecode corresponding to the path.

**Comment by antonmedv** [comment]
I don’t understand what you’re trying to do. Please, provide example code.

**Comment by antonmedv** [comment]
Fill free to reopen the issue if this is an issue.
