### ISSUE TITLE
v2 go mod issue

### ISSUE THREAD

**Issue by ccamel** [antonmedv/expr#46]
I'm wondering if version v2 of the project is available as a go module?

See the following error:
```
$ take foo
$ go mod init
$ go get gopkg.in/antonmedv/expr.v2
go: gopkg.in/antonmedv/expr.v2@v2.0.5: go.mod has non-....v2 module path "github.com/antonmedv/expr" at revision v2.0.5
go: error loading module requirements
```

Thanks!

**Comment by antonmedv** [comment]
Try `go get github.com/antonmedv/expr`.

**Comment by ccamel** [comment]
@antonmedv yes, it works. This is the version I currently use, but [renovate](https://github.com/marketplace/renovate) bot wants to update it, and it fails doing so.

Hence my question: is `github.com/antonmedv/expr` the latest version available?

**Comment by antonmedv** [comment]
Yes. I use tags as well. https://github.com/antonmedv/expr/releases

**Comment by ccamel** [comment]
Ok. It's clear to me. Thanks.
