### ISSUE TITLE
Comparing Alias Types doesn't work

### ISSUE THREAD

**Issue by roblovelock-mpn** [antonmedv/expr#461]
The compiler currently doesn't distinguish between `string` and types aliasing `string` (this also applies to other built in types). The resulting program will try to run an `OpEqualString`, which fails to cast the aliased type to a `string`.

Here are some tests to reproduce the issue:
```go
package alias

import (
	"github.com/antonmedv/expr"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestRun_StringEqual(t *testing.T) {
	type EnvStr string
	type EnvField struct {
		S   EnvStr
		Str string
	}
	type Env struct {
		S        EnvStr
		Str      string
		EnvField EnvField
	}
	var tests = []struct {
		input string
		env   Env
		want  bool
	}{
		{
			input: "Str == S",
			env:   Env{S: "string", Str: "string"},
			want:  false,
		},
		{
			input: "Str == Str",
			env:   Env{Str: "string"},
			want:  true,
		},
		{
			input: "S == S",
			env:   Env{Str: "string"},
			want:  true,
		},
		{
			input: `Str == "string"`,
			env:   Env{Str: "string"},
			want:  true,
		},
		{
			input: `S == "string"`,
			env:   Env{Str: "string"},
			want:  false,
		},
		{
			input: "EnvField.Str == EnvField.S",
			env:   Env{EnvField: EnvField{S: "string", Str: "string"}},
			want:  false,
		},
		{
			input: "EnvField.Str == EnvField.Str",
			env:   Env{EnvField: EnvField{Str: "string"}},
			want:  true,
		},
		{
			input: "EnvField.S == EnvField.S",
			env:   Env{EnvField: EnvField{Str: "string"}},
			want:  true,
		},
		{
			input: `EnvField.Str == "string"`,
			env:   Env{EnvField: EnvField{Str: "string"}},
			want:  true,
		},
		{
			input: `EnvField.S == "string"`,
			env:   Env{EnvField: EnvField{Str: "string"}},
			want:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			program, err := expr.Compile(tt.input, expr.Env(tt.env), expr.AsBool())

			out, err := expr.Run(program, tt.env)
			require.NoError(t, err)

			require.Equal(t, tt.want, out)
		})
	}
}
```

One potential solution would be to remover the cast from `OpEqualString`, but this seemed to have a very slight impact on the benchmarks (one or two nanoseconds)

Another potential solution is to detect alias types at compile time and have them use `OpEqual`.

There are some nuances to any solution:

- When comparing an aliased field to a string field I assume they aren't equal (as the types are different)
- When comparing an aliased field to a string constant I assume they aren't equal (as the types are different), maybe in this instance they should be equal?

**Comment by bjwrk** [comment]
I arrived at this issue while trying to work out if it was expected that comparing an aliased string to an underlying equal constant string produced `false` in `expr`. The test case for this seems to confirm that it is indeed expected, but I'm not sure that it's very ergonomic. `(S == "string") == false` seems wrong to me, I would expect this to return true without requiring wrapping `S` in `string()`. This is how Go behaves with untyped constants.

**Comment by antonmedv** [comment]
Expr uses reflect.DeepEqual underneath and looks like it is false: reflect.DeepEqual

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	type S string
	var str S = "str"
	fmt.Println(reflect.DeepEqual(str, "str")) // false
}

```

**Comment by TcM1911** [comment]
@antonmedv, is the design with Expr to not support string derived types to match when compare to a primitive string? I still see the same issue in the latest version:
```
func TestStringCmp(t *testing.T) {
	is := is.New(t)
	type T string
	type S struct {
		Field T
	}

	// Fails
	shouldBeTrue, err := expr.Eval(`Field == "foobar"`, S{Field: "foobar"})
	is.NoErr(err)
	is.True(shouldBeTrue.(bool))

	// Works
	isTrue, err := expr.Eval(`string(Field) == "foobar"`, S{Field: "foobar"})
	is.NoErr(err)
	is.True(isTrue.(bool))
}
```
If `reflect.DeepEqual` is used, it will return false because:
> Other values - numbers, bools, strings, and channels - are deeply equal if they are equal using Go's == operator. 
and T("foobar") == "foobar" => is false.

I can see how casting it to a string can work but how can an "in" statement be performed? For example:
`"foo" in Bar` where `Bar []T`
