### ISSUE TITLE
Patching MemberNode

### ISSUE THREAD

**Issue by kushsharma** [antonmedv/expr#463]
Earlier the library used to have two different nodes, `PropertyNode` and `MemberNode` but they got merged in one `MemberNode`. Is there any way to differentiate between the two during patching(Visit)? For example if there are two expressions: `foo.bar.hello` and `foo.bar.hello()`, both of them leads to `MemberNode` for `hello` in ast.

**Comment by antonmedv** [comment]
Difference b/ prop and method is CallNode. Property is wrapped in it:

```go
CallNode{
	Callee: MemberNode{
		Node: MemberNode{
			Node: IdentifierNode{"foo"},
			Property: StringNode{"bar"},
		},
		Property: StringNode{"hello"},	
	},
	Arguments: []ast.Node{},
}
```

**Comment by kushsharma** [comment]
Not the best way I guess but it will do. Thanks for the library.
