### ISSUE TITLE
cannot fetch Value from *interface

### ISSUE THREAD

**Issue by a-peyrard** [antonmedv/expr#466]
First of all, thanks for you amazing library!

I'm facing some error when I'm using some dynamic unmarshalling of protobuf messages in the program context, the unmarshalled types are `interface{} | *interface{} | *<STRUCT CONCRETE TYPE>`.
When I'm trying to access a field of the struct, I'm getting the error: `cannot fetch Value from *interface{}`.

Here is a concrete example where I'm reproducing the error:
```go
func TestExpr_fetch_from_interface(t *testing.T) {
	type FooBar struct {
		Value string
	}
	foobar := &FooBar{"waldo"}
	var foobarAny any = foobar
	var foobarPtrAny any = &foobarAny

	res, err := expr.Eval("foo.Value", map[string]any{
		"foo": foobarPtrAny,
	})
	assert.NoError(t, err)
	assert.Equal(t, "waldo", res)
}
```
And the error is:
```
=== RUN   TestExpr_fetch_from_interface
    expr_test.go:1218: 
        	Error Trace:	/opt/dev/go/expr/expr_test.go:1218
        	Error:      	Received unexpected error:
        	            	cannot fetch Value from *interface {} (1:5)
        	            	 | foo.Value
        	            	 | ....^
        	Test:       	TestExpr_fetch_from_interface
    expr_test.go:1219: 
        	Error Trace:	/opt/dev/go/expr/expr_test.go:1219
        	Error:      	Not equal: 
        	            	expected: string("waldo")
        	            	actual  : <nil>(<nil>)
        	Test:       	TestExpr_fetch_from_interface
--- FAIL: TestExpr_fetch_from_interface (0.00s)
```

This was working fine with `v1.12.5` but this not working anymore with `v1.15.3`.

The error is triggered in the `Fetch` method, here: https://github.com/antonmedv/expr/blob/5916dc2b68d01606f6c23e1b54da5ee3cd3dc79a/vm/runtime/runtime.go#L76

I'm wondering a simple fix could be to use a deref function like that:
```go
func deref(kind reflect.Kind, value reflect.Value) (reflect.Kind, reflect.Value) {
	for kind == reflect.Ptr || kind == reflect.Interface {
		value = value.Elem()
		kind = value.Kind()
	}
	return kind, value
}
```
And use it instead of the `if` block here: https://github.com/antonmedv/expr/blob/5916dc2b68d01606f6c23e1b54da5ee3cd3dc79a/vm/runtime/runtime.go#L28-L34

Thanks for your help.

Happy to submit a PR with the fix if the `deref` solution is a valid option, or to implement any other idea for the fix.

**Comment by antonmedv** [comment]
Hi, yes we need to this it. It was working in v1.12 as it has similar deref function. In v1.15 it was replaced by OpDeref opcode to speedup VM for value what do not need dereferencing (-5% speedup). So, we can simply return this function without losing some pref. 

A proper solution will be to understand why OpDeref is not added here. You can start by dumping opcodes of compiled program.

**Comment by a-peyrard** [comment]
Thanks for your response. I'm preparing a PR with the fix in fetch.

I was also looking at the `OpDeref` and why it is not added, and while looking at that I also found that `runtime.Deref` was not capable of de-referencing pointer of interface, so I fixed that in the PR.
I also might have find another case where we are missing an `OpDeref`:
```go
func TestDeref_in_cast(t *testing.T) {
	t.Run("cast int should deref **string", func(t *testing.T) {
		a := "42"
		b := &a
		c := &b
		output, err := expr.Eval(`int(c)+2`, map[string]any{
			"c": c,
		})
		require.NoError(t, err)
		require.Equal(t, 44, output)
	})

	t.Run("cast int should deref pointer of interface", func(t *testing.T) {
		a := "42"
		b := any(a)
		c := any(&b)
		output, err := expr.Eval(`int(c)+2`, map[string]any{
			"c": c,
		})
		require.NoError(t, err)
		require.Equal(t, 44, output)
	})
}
```
Those tests are both failing.

Once I submit the initial PR, I will try to have a look to understand why `OpDeref` was not added.

**Comment by antonmedv** [comment]
Fixed!
