### ISSUE TITLE
Expose error type

### ISSUE THREAD

**Issue by bontibon** [antonmedv/expr#47]
Currently, returned errors are of type `*errors.errorString`. This prevents inspection of the error to get specific details. For example, to isolate the message, location, and source code of the error. Something along the lines of:

```go
result, err := expr.Eval(`"test" + 3`, nil)
if err != nil {
    if exprErr, ok := err.(expr.Error); ok {
        // exprErr.Message
        // exprErr.Location
        // exprErr.Source
        // ...
    }
}
```

**Comment by antonmedv** [comment]
Hm, it will be cool to have.

**Comment by antonmedv** [comment]
Done! Now file package is top level.
