### ISSUE TITLE
How to replace identifier nodes in expression?

### ISSUE THREAD

**Issue by techbobo** [antonmedv/expr#48]
I used ast.walk function, I can find all identifier nodes in expression. 
But I want to replace some identifier nodes, then generate new expression, then compare it.
How is this achieved?

**Comment by antonmedv** [comment]
Simple replace it in visitor. Or you trying to stringify expression?

**Comment by techbobo** [comment]
How can I replace it in visitor and then run new expression?

**Comment by antonmedv** [comment]
Just replace node in visitor.

**Comment by techbobo** [comment]
It generate new Tree when replace some node.
How can I complie use new Tree?
Do you have example code?
Thank you.

**Comment by antonmedv** [comment]
You can compile tree to a program
```go
	program, err := compiler.Compile(tree, config)
```

Take a look at Eval func https://github.com/antonmedv/expr/blob/master/expr.go#L15-L32

**Comment by techbobo** [comment]
Thank you very much, I know how to do it.

**Comment by leopku** [comment]
Hi @techbobo . Could you told me how to do it? Thanks. I'm now troubling same issue.

**Comment by antonmedv** [comment]
@leopku https://expr-lang.org/docs/v1.15/visitor-and-patch
