### ISSUE TITLE
Allow a VM instance to be reused

### ISSUE THREAD

**Issue by deanm** [antonmedv/expr#58]
Right now it looks like a VM instance cannot be re-used (is this correct?), it seems like there is no way to reset the instruction pointer / stack / etc, so the only option is to dynamically allocate and construct and entirely new VM instance for each execution (which also involves dynamically allocating heap memory for the stack, making channels, etc).  If you want to run the same expression over large amounts of data it seems like you would want to be able to reuse the VM.

**Comment by deanm** [comment]
#59

**Comment by antonmedv** [comment]
Done!
