### ISSUE TITLE
Parser error on 386 arch by int overflows

### ISSUE THREAD

**Issue by r3code** [antonmedv/expr#64]
Windows 7 32-bit
go1.11.2 windows/386
Trying to do:
```
package main

import (
	"github.com/antonmedv/expr"
)

func main() {
	p, err := expr.Compile("1+2") 
}

```
Build fails with multiple errors:
```
Installation failed: # github.com/antonmedv/expr/parser/gen
..\..\..\..\github.com\antonmedv\expr\parser\gen\expr_parser.go:2231: constant 4228579072 overflows int
..\..\..\..\github.com\antonmedv\expr\parser\gen\expr_parser.go:2249: constant 4228579072 overflows int
..\..\..\..\github.com\antonmedv\expr\parser\gen\expr_parser.go:2300: constant 4228579072 overflows int

```

**Comment by antonmedv** [comment]
Looks like Antlr generated code doesn't support 32 bit arch. I think this is Antlr issue.

**Comment by r3code** [comment]
@antonmedv I tried to update Go.
Now `go version go1.12.9 windows/386` at one PC with Win 7 32bit it fails and at another it works (the same OS version).
How can I help to debug it? 

Антон, на одной машине у нас все ОК, на другой такая ошибка. Может как то заставить Antlr перегенерировать код?

**Comment by r3code** [comment]
@antonmedv the related issue in Antlr https://github.com/antlr/antlr4/issues/2433

**Comment by antonmedv** [comment]
Yes, I think this is only possible to solve it, by solving issue at Antlr. It's really difficult to patch already generated code.

**Comment by r3code** [comment]
@antonmedv Strange to see when at one computer it works and at another it fails... looks odd

**Comment by antonmedv** [comment]
Yes, but `4228579072  >  2^32` is overflow.

**Comment by 1xch** [comment]
I just got this very same error after updating to go1.13.

**Comment by hoshsadiq** [comment]
This antlr project doesn't seem to be very interested in this issue, I'm thinking, would it make sense to enforce int32 everywhere within this package?

**Comment by antonmedv** [comment]
Hmm, why to enforce? I’m thinking about rewriting parser from the scratch actually.

**Comment by hoshsadiq** [comment]
I guess my thinking is a bit premature without actually doing any research. I guess I was thinking that since this is an overflow error, it's likely that somewhere in this package int/int64 was used that then is passed into antlr. But once I read your comment I realised that this could equally be happening inside the antlr project.

**Comment by antonmedv** [comment]
Fixed.

I've rewritten the entire parser for this. :)

**Comment by r3code** [comment]
@antonmedv Is it here https://github.com/antonmedv/expr/commit/a3582e9c6d39193a53f7bc0082e94d117384970c ?

**Comment by antonmedv** [comment]
Yes.

**Comment by r3code** [comment]
Спасибо!
