### ISSUE TITLE
Compile method was renamed?

### ISSUE THREAD

**Issue by r3code** [antonmedv/expr#65]
I see in doc and usage examples `Compile` calls but trying to run an example fails with `undefined expr.Compile`.
I have github.com/antonmedv/expr v1.1.4
`go doc expr` says:
```
  // Or precompile expression to ast first.
    node, err := expr.Parse("expression")
```

May be docs should be updated?

**Comment by antonmedv** [comment]
Yes, at 2.x API was changed. See https://github.com/antonmedv/expr/releases/tag/v2.0.0
Maybe I need to keep CHANGES.md and UPGRADE.md files.

**Comment by r3code** [comment]
@antonmedv Also https://github.com/antonmedv/expr/tree/master/docs and root Readme

**Comment by antonmedv** [comment]
docs are updated and using `expr.Compile`.
