### ISSUE TITLE
Getting an error from a called function inside expression language.

### ISSUE THREAD

**Issue by mineyev** [antonmedv/expr#66]
Hi, how i can get an error from result of function inside expression language?

Case:

	package main

	import (
	    "errors"
	    "fmt"
	    "github.com/PaesslerAG/gval"
	    "github.com/antonmedv/expr"
	)

	type A struct {}

	func (a *A) Test() (string, error) {
	    return "test", errors.New("it`s error!")
	}

	func main() {
	    a := A{}

	    val, err := expr.Eval(`tx.Test()`, map[string]interface{}{
		"tx": &a,
	    })

	    fmt.Println(val) //print test
	    fmt.Println(err) //print <nil>
	}

	//need:

	    val, err = gval.Evaluate(`tx.Test()`, map[string]interface{}{
		"tx": &a,
	    })

	    fmt.Println(val) //print <nil>
	    fmt.Println(err) //print can not evaluate tx.Test(): it`s error!
}

**Comment by antonmedv** [comment]
Hi, this is a good question. I think I forgot to mention this in docs. Expr expects functions to return a single value. To notify an error, you can use panic. Expr uses recover.

For example, if your function going to divide by zero `1/0` Expr will also work correctly as it will panic.

**Comment by antonmedv** [comment]
Now function can return single value and panic, or return (T, error).
