### ISSUE TITLE
'constant overflows int' after update to go1.13

### ISSUE THREAD

**Issue by 1xch** [antonmedv/expr#67]
On update to go1.13, a package using generated code begins to error

```
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2231: constant 4228579072 overflows int
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2249: constant 4228579072 overflows int
/home/o/go/src/github.com/antonmedv/expr/parser/gen/expr_parser.go:2300: constant 4228579072 overflows int
```

There was no problem previously until the update, i was using the expr package and have almost zero experience with the details this deep but thought it might be wise to post an issue here.

**Comment by r3code** [comment]
It can be related to the issue https://github.com/golang/go/issues/33388
