### ISSUE TITLE
Another go.mod v2 issue?

### ISSUE THREAD

**Issue by starbuck-ms** [antonmedv/expr#68]
We have been using v1.1.4 of the 'expr' package, which is great, by the way. We finally updated to GO 1.13 and at the same time started migrating to GO modules. 

However, when upgrading, our process is failing because of a missing "/v2" in your go.mod module path. 

```text
$ go get github.com/antonmedv/expr@v2.1.1
go: finding github.com v2.1.1
go: finding github.com/antonmedv v2.1.1
go: finding github.com/antonmedv/expr v2.1.1
go: finding github.com/antonmedv/expr v2.1.1
go get github.com/antonmedv/expr@v2.1.1: github.com/antonmedv/expr@v2.1.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I was able to download the source and modify the "go.mod" file to be:

```text
$ cat go.mod
module github.com/antonmedv/expr/v2

go 1.12

require (
	github.com/antlr/antlr4 v0.0.0-20190518164840-edae2a1c9b4b
	github.com/gdamore/tcell v1.1.2
	github.com/rivo/tview v0.0.0-20190515161233-bd836ef13b4b
	github.com/sanity-io/litter v1.1.0
	github.com/stretchr/testify v1.3.0
	golang.org/x/text v0.3.2
)
```

This helped me get past the above error.

Is there something I am doing wrong? Or is this an issue with the "expr" module. I am new to "go modules" and dealing with the learning curve.

**Comment by antonmedv** [comment]
Hi,

Just checked the installation of expr on go 1.12 and 1.13. Everything is working for me. 

Let's find out what is causing your problems.

**Comment by starbuck-ms** [comment]
Thanks, I now have a working configure. However... when moving to "@v2.1.1" GO would complain about invalid version in the go.mod "module" line. I updated the go.mod file to:

```text
module github.com/antonmedv/expr/v2
```

But then I started getting call kinds of other errors:

```text
$ go get -u github.com/antonmedv/expr/v2@v2.1.2
go: finding github.com v2.1.2
go: finding github.com/antonmedv v2.1.2
go: finding github.com/antonmedv/expr v2.1.2
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:7:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/checker
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:8:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/compiler
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:9:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/internal/conf
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:10:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/optimizer
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:11:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/parser
/go/modules/pkg/mod/github.com/antonmedv/expr/v2@v2.1.2/expr.go:12:2: module github.com/antonmedv/expr@latest (v1.1.4) found, but does not contain package github.com/antonmedv/expr/vm
```

I then changed all of the import lines to be the following based on: https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning,

```go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"github.com/antonmedv/expr/v2"
	"github.com/antonmedv/expr/v2/checker"
	"github.com/antonmedv/expr/v2/compiler"
	"github.com/antonmedv/expr/v2/optimizer"
	"github.com/antonmedv/expr/v2/parser"
	"github.com/sanity-io/litter"
	"io/ioutil"
	"os"
)
```

And had more success. I was able to finally integrate that into our code base.

Another package we use, "echo labstack", already modified their source code to use "/v4" in all their internal module import paths.

Here is an example source file: https://github.com/labstack/echo/blob/master/middleware/cors.go

And here is their "go.mod" file, https://github.com/labstack/echo/blob/master/go.mod

It would be interesting to see what you are doing when you integrate the "expr" module into another package. What does your go.mod file look like?

**Comment by antonmedv** [comment]
Hmm, I only used go.mod for a project before. Never in a third-party module. Will try to do it as well.

**Comment by fatslo** [comment]
I am having same issues being outside GOPATH and using go1.13.1.

If i understand correctly, the golang team introduced the concept of semantic import versioning in their mod system, which means that publishing and importing module versions higher or equal 2.0.0 has to be treated different to versions 0.x.x or 1.x.x.
See [https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)

**Comment by antonmedv** [comment]
Okay, now I understand. I see two possibilities:

1. Replace all with `github.com/antonmedv/expr/v2`.
2. Ignore BC, and tag new release with v1.2

**Comment by antonmedv** [comment]
I've introduced v1.2.0 release which is backward compatible with all v1 versions.

**Comment by starbuck-ms** [comment]
Thank you for looking into this and finding a solution!

**Comment by antonmedv** [comment]
Does it work now? Can we close this issue?

**Comment by fatslo** [comment]
works with v1.2.0, thank you.
