### ISSUE TITLE
Can't get simple test case to work

### ISSUE THREAD

**Issue by payneio** [antonmedv/expr#69]
Seems straightforward, but for the life of me, can't get this to work. Keep getting `ca_test.go:19: Expected no errors. Got: undefined: beliefs`:
```
func TestExpr(t *testing.T) {
	expression := "beliefs['temp'] > 60 and beliefs['temp'] < 76"
	env := map[string]interface{}{
		`beliefs`: map[string]interface{}{
			`temp`: 58.6,
		},
	}
	out, err := expr.Eval(expression, expr.Env(env))
	if err != nil {
		t.Errorf("Expected no errors. Got: %v", err)
	}
	if out != false {
		t.Errorf("Expecte `false`, got: %v", out)
	}
}
```

**Comment by antonmedv** [comment]
Hi,

Try this fix:
```diff
	expression := "beliefs['temp'] > 60 and beliefs['temp'] < 76"
	env := map[string]interface{}{
		`beliefs`: map[string]interface{}{
			`temp`: 58.6,
		},
	}
-	out, err := expr.Eval(expression, expr.Env(env))
+	out, err := expr.Eval(expression, env)
	if err != nil {
		t.Errorf("Expected no errors. Got: %v", err)
	}
	if out != false {
		t.Errorf("Expecte `false`, got: %v", out)
	}
```

**Comment by antonmedv** [comment]
Also, I've added check what in future this misused will be notified 4d40254bf70e2ba6f90dea9cc5d36e96336bbe84

**Comment by payneio** [comment]
Yes... I've been working it today without the Env wrapper and it works fine. What is the point of the Env wrapper then? It creates a type table of some sort?

**Comment by antonmedv** [comment]
Yes, `expr.Env` creates type tables for type checker. Take a look at this example: https://godoc.org/github.com/antonmedv/expr#example-Compile
Compile ahead of time will allow faster execution and type checking of expression before going to production.

**Comment by payneio** [comment]
I see... so I only use it with Compile, and not with Eval.

P.
