### ISSUE TITLE
Forbid access to private fields ?

### ISSUE THREAD

**Issue by simon-vasseur** [antonmedv/expr#78]
First, congrats for this really nice project :)

For my use case I need to disallow access to private fields (recursively). Is there currently any way to do that? Thanks.

**Comment by antonmedv** [comment]
Hi, thanks!

This is, actually, default behavior. Example:
```go
	type env struct {
		private int
	}

	program, err := expr.Compile(`private`, expr.Env(env{}))
	require.NoError(t, err)

	output, err := expr.Run(program, env{private: 42})
	require.NoError(t, err)
	require.Equal(t, 42, output)
```

**Comment by simon-vasseur** [comment]
Arf :( My bad

A go get -u ... fixed the problem. Maybe related to this commit ? https://github.com/antonmedv/expr/commit/54e885c27967ebe13e0eb580ebae5a267fbf3bb1

**Comment by antonmedv** [comment]
Hmm, I don’t think so.

**Comment by simon-vasseur** [comment]
OK well, anyway it's fixed now. Sorry for the noise .. Thanks for your time
