### ISSUE TITLE
Can expr return a pointer ?

### ISSUE THREAD

**Issue by JohnDoeCrowdSec** [antonmedv/expr#81]
Hello,

First of all thanks for this great project :)

I was wondering if Expr can be used to return a pointer to a field of a structure rather than its value ?

Let's say I let the user specifiy source and destination fields in some kind of configuration (strings only for the example).

When it comes to specifying the source, expr already handles this, as the user can write `foo.bar.baz` and expr will return the string contained in `baz`.

However, I'd like for expr to be able to return the address of `baz` so I can do other stuff with it (for example write to it).

Is it something possible ?

Thanks,

**Comment by antonmedv** [comment]
Hello,

I think currently this is now possible. There is no`&` API in expr.

**Comment by JohnDoeCrowdSec** [comment]
You mean **not** possible ?

Do you forsee this hapening any time soon ?
Or should I go down the road of a home-made reflect parser to achieve this ?

Best regards !

**Comment by antonmedv** [comment]
Yes, I don't have any plans for adding this functionality. Maybe if more people will request it. Or I can work on this issue for money if you want it to be implemented in expr now.
