### ISSUE TITLE
Proposal: extending Regexp support

### ISSUE THREAD

**Issue by tigrannajaryan** [antonmedv/expr#82]
@antonmedv: First of all, thank you for a great library! I played with it a bit and it is very nicely done.

One thing that looks a bit limited is Regexp support. From what I see the only supported operation is currently string `match` which takes a regexp string on the right-hand side.

Would you be interested in enhancing Regexp support? I will be happy to contribute PRs that implement new features. Here is what I would love to see added:

- Add Regexp as native supported type with a set of simple functions, e.g. FindMatches, FindSubmatches, etc. that implement more complex functionality related to regexes.

- Regexp literal support (e.g. JavaScript-like forward slash-based). 
Yes, one can define a custom `Regexp()` function which accepts a regex string and creates a Regex type, but that will only work dynamically. With literal support it would be possible to pre-compile regexes.

Is this something you would be interested in adding to the language? I am currently considering using Expr in a product I work on and these capabilities are what I am missing to move forward. I can implement the features myself but wanted to check first if this is inline with how you want to evolve the library.

Thanks again :)

**Comment by antonmedv** [comment]
Hi @tigrannajaryan,

I'm very cautious with adding functionality to default language (as it may be used un may different ways across dozens of companies right now). Every additional feature has it's costs and compromises. For example, there is not even data/time functionality builtin in the language (I'm also investigating the need for this). 

But the Expr package has a great support for extendability. Everything can be added as helper functions. So first let's try to understand what is your demand and what kind of problem do you trying to solve? What is the use case? Can it be solved with the current set of functionality? 

> Yes, one can define a custom Regexp() function which accepts a regex string and creates a Regex type, but that will only work dynamically. With literal support it would be possible to pre-compile regexes.

This is also a good case. Maybe we can solve more general problems with adding ability precompile any part of expressions based on some pattern?

**Comment by tigrannajaryan** [comment]
> This is also a good case. Maybe we can solve more general problems with adding ability precompile any part of expressions based on some pattern?

One of my use cases is to be able to match a string against a regular expression and extract matched subexpression. I can achieve that by defining in my Env a `Regexp()` function that returns a compiled `Regexp` struct and then define for example a `func (Regexp) Submatch(str string)` function  that extracts a subexpression from `str`. After that my expression can be written like this:

`Regexp("mysuper(.*)regex").Submatch(SomeVarName)`

This works. I tried it and it is easy to implement. I agree that Expr has great extendability support.

One problem with this is that `Regexp("mysuper(.*)regex")` is evaluated every time I call `expr.Run`. It is not precompiled, since it is a function call. This makes it slow if I need to compile once and run many times. My `expr.Run` is in a tight loop that needs to execute at >100K/sec rates, so it needs to run as fast as possible and precompiling regular expression is very important.

One possible approach to avoid this problem that I suggested in my first post is to make sure regular expression is precompiled by adding support for regexp literals and then use something like `/mysuper(.*)regex/.Submatch(SomeVarName)` instead.

However, I understand that you may not want to add too many features and regexp literals may not fit your vision for the library.

An alternate approach would be to allow the Env to declare that certain functions are `constexpr` (if I may borrow C++ terminology). So, for example I could declare in my Env that `Regexp()` is a constexpr, i.e. its value depends only on its arguments and thus can be executed at compile time. In that case `expr.Compile` would execute that portion of sub-expression at compile time.

The rule could be that if a function is marked `constexpr` and its arguments are also constants then evaluation is done at compile-time.

**Comment by antonmedv** [comment]
Actually I like both of your suggestions. Let’s think of what we could implement first. I think I can help with some parts.

**Comment by antonmedv** [comment]
#84

**Comment by tigrannajaryan** [comment]
Thank you. For the particular feature I am implementing I ended up not using a generic expression evaluator, so I no longer have an immediate need for this. However I believe this can be a very useful feature.

**Comment by antonmedv** [comment]
Yes, I really like constexpr feature and will implement it. Regexp support not for now.

**Comment by antonmedv** [comment]
See #96
