### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jscoys** [antonmedv/expr#93]
Hello guys!

Would like to do simple assignation évaluation, something like:

Var lib string
Code = ‘lib="ok"’
... expr code to parse this thing...
Font.Println(lib) // should print ok

Is it something doable? If yes what code should i use to achieve that?

**Comment by antonmedv** [comment]
You can do something [like this](https://play.golang.org/p/qzGsHpXtBsq):
```go
	var lib string
	code := `"ok"`

	output, _ := expr.Eval(code, nil)
	lib = output.(string)

	fmt.Println(lib)
```

**Comment by jscoys** [comment]
Hum the example was not exactly what I need in fact, but it’s my fault, I took a too simple example.

Let’s say I have an type library interface{}, then I have different type xxx struct implementing the lib’s func, so I have a kind of polymorphism.

To implement it I have this code:

Var lib library

lib = &xxx{} // I would like to define dynamically the "xxx" through a string for instance

fmt.Println(lib.getVar()) // will use implementation of getVar() from xxx type.

Thx!

**Comment by antonmedv** [comment]
Still didn't understand. ¯\_(ツ)_/¯

**Comment by jscoys** [comment]
Hello here is a complete code. Look at my comment and tell me if it’s possible or not:

package main

import "fmt"

type library interface{
    getVal() int
}

type movie struct{
    ID int
}

type music struct{
    MusicID int
}

func (mv *movie) getVal() int{
    return 8
}

func (mv music) getVal() int{
    return 1
}

func main() {
    var lib library
    lib = &movie{} // I Would like to be able to eval this assignation at the runtime, so evaluate a string like str := "lib = &movie{}" and then execute this string like it was code
    
    fmt.Println(lib.getVal())
    
    lib = &music{}
    
    fmt.Println(lib.getVal())
    
}

**Comment by antonmedv** [comment]
It's possible with some tweaks: `SetLib(Music())`

**Comment by jscoys** [comment]
Hum ok and what is doing SetLib?

**Comment by jscoys** [comment]
Oh ok so if I understand well we can eval SetLib right?

**Comment by antonmedv** [comment]
func SetLib(l library) {
lib:=l
}
env=map{"SetLib": SetLib}
