### ISSUE TITLE
Parser behavior change in 1.5

### ISSUE THREAD

**Issue by zugl** [antonmedv/expr#94]
At v1.5.7 the parser no longer accepts trailing commas for maps and lists:
```
[1, 2, 3,]

{"a": 1, "b": 2, "c": 3,}
```

Now running these expressions returns:

- lists: `unexpected token Bracket(\"]\")`
- maps: `a map key must be a quoted string, a number, a identifier, or an expression enclosed in parentheses (unexpected token Bracket(\"}\"))`

Is this expected? I got these errors after upgrading from v1.4.1 and there was no problem before.

Thanks in advance.

**Comment by antonmedv** [comment]
Parser was rewritten in fix some bugs. This is new one, so PR is needed. Will do it tomorrow.

**Comment by antonmedv** [comment]
Fixed in b72131bcd6496f2e1b22eb7c7f19540d79c3d7a3
